-- GRT Employee Lifecycle Ecosystem — 员工生命旅程生态系统 (G1–G20)
-- Mission: 做全球最好的工业洁净系统 | Philosophy: 工程师文化 · 公平公开学习

-- ── Journey Master Record ──
CREATE TABLE IF NOT EXISTS lifecycle_journeys (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  employee_id VARCHAR(50),
  employee_name VARCHAR(100) NOT NULL,
  department VARCHAR(100),
  position VARCHAR(100),
  role VARCHAR(50),
  hire_date TIMESTAMP,
  current_stage VARCHAR(10) NOT NULL DEFAULT 'G2',
  current_stage_name VARCHAR(100),
  stage_entered_at TIMESTAMP DEFAULT NOW(),
  portal_theme VARCHAR(30) DEFAULT 'default',
  portal_banner_url VARCHAR(500),
  personal_motto VARCHAR(300),
  career_vision TEXT,
  personal_highlight_reel JSON DEFAULT '[]',
  company_mission_acknowledged BOOLEAN DEFAULT FALSE,
  culture_values JSON DEFAULT '[]',
  persona_traits JSON,
  status VARCHAR(20) DEFAULT 'active',
  exit_date TIMESTAMP,
  alumni_status VARCHAR(20),
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);
CREATE UNIQUE INDEX lj_user_idx ON lifecycle_journeys(user_id);
CREATE INDEX lj_stage_idx ON lifecycle_journeys(current_stage);
CREATE INDEX lj_dept_idx ON lifecycle_journeys(department);

-- ── Stage Milestones ──
CREATE TABLE IF NOT EXISTS lifecycle_milestones (
  id SERIAL PRIMARY KEY,
  journey_id INTEGER NOT NULL REFERENCES lifecycle_journeys(id),
  user_id INTEGER NOT NULL REFERENCES users(id),
  stage_code VARCHAR(10) NOT NULL,
  stage_name VARCHAR(100) NOT NULL,
  stage_name_en VARCHAR(100),
  stage_description TEXT,
  stage_icon VARCHAR(50),
  stage_color VARCHAR(20),
  expected_date TIMESTAMP,
  actual_date TIMESTAMP,
  completed_at TIMESTAMP,
  status VARCHAR(20) DEFAULT 'upcoming',
  objectives JSON DEFAULT '[]',
  daily_tools JSON DEFAULT '[]',
  reporting_requirements JSON DEFAULT '[]',
  inspirational_message TEXT,
  mentor_message TEXT,
  media_url VARCHAR(500),
  media_type VARCHAR(20),
  achievement_badge VARCHAR(100),
  achievement_title VARCHAR(200),
  stage_kpi_score DECIMAL(5,2),
  stage_capability_level INTEGER,
  manager_review TEXT,
  manager_reviewed_by INTEGER REFERENCES users(id),
  manager_reviewed_at TIMESTAMP,
  manager_rating INTEGER CHECK (manager_rating >= 1 AND manager_rating <= 5),
  hrbp_notes TEXT,
  hrbp_reviewed_by INTEGER REFERENCES users(id),
  hrbp_reviewed_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);
CREATE UNIQUE INDEX lm_journey_stage_idx ON lifecycle_milestones(journey_id, stage_code);
CREATE INDEX lm_user_idx ON lifecycle_milestones(user_id);
CREATE INDEX lm_status_idx ON lifecycle_milestones(status);

-- ── Journey Activities ──
CREATE TABLE IF NOT EXISTS lifecycle_activities (
  id SERIAL PRIMARY KEY,
  journey_id INTEGER NOT NULL REFERENCES lifecycle_journeys(id),
  user_id INTEGER NOT NULL REFERENCES users(id),
  stage_code VARCHAR(10),
  activity_type VARCHAR(30) NOT NULL,
  title VARCHAR(300) NOT NULL,
  description TEXT,
  metadata JSON,
  impact_score INTEGER,
  is_public BOOLEAN DEFAULT TRUE,
  is_pinned BOOLEAN DEFAULT FALSE,
  image_url VARCHAR(500),
  occurred_at TIMESTAMP DEFAULT NOW(),
  created_at TIMESTAMP DEFAULT NOW()
);
CREATE INDEX la_journey_idx ON lifecycle_activities(journey_id);
CREATE INDEX la_user_idx ON lifecycle_activities(user_id);
CREATE INDEX la_type_idx ON lifecycle_activities(activity_type);
CREATE INDEX la_stage_idx ON lifecycle_activities(stage_code);

-- ── G1-G20 Stage Templates ──
CREATE TABLE IF NOT EXISTS lifecycle_stage_templates (
  id SERIAL PRIMARY KEY,
  stage_code VARCHAR(10) UNIQUE NOT NULL,
  stage_name VARCHAR(100) NOT NULL,
  stage_name_en VARCHAR(100),
  stage_subtitle VARCHAR(300),
  stage_icon VARCHAR(50),
  stage_color VARCHAR(20),
  typical_start_month INTEGER,
  typical_end_month INTEGER,
  description TEXT,
  narrative TEXT,
  company_mission_link TEXT,
  culture_message TEXT,
  default_objectives JSON DEFAULT '[]',
  default_daily_tools JSON DEFAULT '[]',
  default_reporting JSON DEFAULT '[]',
  default_media_url VARCHAR(500),
  default_media_type VARCHAR(20),
  default_message TEXT,
  achievement_badge VARCHAR(100),
  achievement_title VARCHAR(200),
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- ══════════════════════════════════════════════════════════════════
-- SEED: G1-G20 Stage Templates with full narrative content
-- ══════════════════════════════════════════════════════════════════
INSERT INTO lifecycle_stage_templates (stage_code, stage_name, stage_name_en, stage_subtitle, stage_icon, stage_color,
  typical_start_month, typical_end_month, description, narrative, company_mission_link, culture_message,
  default_objectives, default_daily_tools, default_reporting, default_message, achievement_badge, achievement_title, sort_order) VALUES

('G1', '招募吸引', 'Attraction', '你与GRT的缘分开始了', 'Magnet', '#8b5cf6',
 -1, 0,
 '从第一次了解GRT开始，你的旅程已经悄然开启。我们寻找志同道合的工程师伙伴，共同追求卓越。',
 '每一位来到GRT的人，都是被我们的愿景所吸引——做全球最好的工业洁净系统。也许是一次招聘会的偶遇，也许是朋友的推荐，也许是你在行业中对GRT品质的认可。无论如何，这是一段伟大旅程的起点。',
 '我们相信，最优秀的人才是被使命感召，而非仅仅被薪酬吸引。GRT的工程师文化，是我们最强的磁场。',
 '公平公开，以实力说话。在GRT，每一位工程师都有机会证明自己的价值。',
 '[{"role":"ALL","objectives":[{"title":"了解GRT企业文化与使命","type":"culture"},{"title":"完成入职前资料准备","type":"learning"}]}]',
 '[]', '[]',
 '欢迎来到GRT！你的工程师旅程即将启航。做全球最好的工业洁净系统，需要最优秀的你。',
 '🌟 Journey Begins', '旅程启航者', 1),

('G2', '入职启航', 'Onboarding Launch', '第一天，一切从这里开始', 'Rocket', '#3b82f6',
 0, 0,
 '入职第一天，你正式成为GRT大家庭的一员。领取工牌、认识团队、了解你的工作环境。',
 '还记得你第一天走进GRT的感觉吗？崭新的工牌，热情的同事，整洁的车间。这一天，你不再是旁观者，你是GRT故事的共同书写者。从今天起，你的每一份努力，都在为全球最好的工业洁净系统添砖加瓦。',
 '你的双手将触碰到世界一流的洁净设备。每一台从GRT走出的机器，都承载着我们对品质的极致追求。',
 '工程师的第一课：敬畏标准，敬畏品质。每一个螺丝都值得被认真对待。',
 '[{"role":"ALL","objectives":[{"title":"完成入职手册学习","type":"learning","linkedCategoryCode":"HR"},{"title":"熟悉公司安全制度","type":"learning","linkedCategoryCode":"SAFETY"},{"title":"认识直属团队成员","type":"social"},{"title":"设置系统账号与权限","type":"learning"}]}]',
 '[{"tool":"赋能工作台","path":"/personal-dashboard","description":"每日晨报、任务概览、AI助手","frequency":"daily"},{"tool":"企业知识合规","path":"/knowledge-compliance","description":"查阅入职必读文档","frequency":"daily"},{"tool":"员工成长平台","path":"/employee-growth","description":"查看阶段性培训计划","frequency":"weekly"}]',
 '[{"reportType":"daily","frequency":"每日","to":"直属主管"},{"reportType":"weekly","frequency":"入职首周每日","to":"HRBP"}]',
 '从今天起，你是GRT工程师。世界级的品质，从你手中开始。',
 '🚀 Launched', '正式启航', 2),

('G3', '文化融入', 'Culture Immersion', '理解GRT的灵魂', 'Heart', '#ec4899',
 0, 0,
 '入职第1-2周，深入了解GRT的文化DNA：工程师精神、品质至上、团队协作、持续改善。',
 'GRT不只是一家公司，它是一个追求极致的工程师社区。在这两周里，你会发现：为什么我们对清洁度如此执着？为什么每一台设备出厂前都要经过严苛测试？因为我们的客户信任我们，而我们绝不辜负这份信任。',
 '全球最好的工业洁净系统——这不是口号，而是每天的行动。从5S到IATF 16949，从车间到办公室，品质无处不在。',
 '学习是GRT人的生活方式。在这里，提问不是弱点，不学习才是。公平公开的环境，让每个人都能放心成长。',
 '[{"role":"ALL","objectives":[{"title":"参加企业文化宣讲","type":"culture"},{"title":"学习5S管理规范","type":"learning","linkedCategoryCode":"SAFETY"},{"title":"了解公司产品线","type":"learning","linkedCategoryCode":"PRODUCT"},{"title":"参观车间与展厅","type":"culture"},{"title":"完成保密合规培训","type":"learning","linkedCategoryCode":"COMPLY"}]}]',
 '[{"tool":"企业知识合规","path":"/knowledge-compliance","description":"系统学习公司规章制度","frequency":"daily"},{"tool":"赋能工作台","path":"/personal-dashboard","description":"每日工作报告提交","frequency":"daily"},{"tool":"社区交流","path":"/social-community","description":"认识跨部门同事","frequency":"weekly"}]',
 '[{"reportType":"daily","frequency":"每日","to":"直属主管"}]',
 '当你理解了GRT的灵魂，你就找到了自己在这里的意义。',
 '❤️ Culture Native', '文化融入者', 3),

('G4', '技能筑基', 'Skill Foundation', '打下坚实的专业基础', 'Hammer', '#f59e0b',
 1, 1,
 '入职第1个月，系统学习岗位所需的基础技能：设备操作、SOP流程、质量标准、安全规范。',
 '一座大厦的高度，取决于地基的深度。在GRT，我们相信扎实的基础功比花哨的技巧更重要。这个月，你要像海绵一样吸收知识——SOP不是约束，而是前辈们用经验和教训换来的智慧结晶。',
 '每一份SOP背后，都有一个关于品质的故事。学习它、理解它、执行它——这就是工程师的基本素养。',
 '不懂就问，问了就学，学了就练，练了就会。GRT工程师的成长之道，就是这么朴素。',
 '[{"role":"ALL","objectives":[{"title":"完成岗位SOP全部学习","type":"learning","linkedCategoryCode":"SOP"},{"title":"通过安全生产理论测试","type":"certification","linkedCategoryCode":"SAFETY"},{"title":"掌握ERP基本操作","type":"learning","linkedCategoryCode":"TRAIN"},{"title":"完成至少1个实操考核","type":"certification"}]}]',
 '[{"tool":"企业知识合规","path":"/knowledge-compliance","description":"完成Lv1必学文档","frequency":"daily"},{"tool":"赋能工作台","path":"/personal-dashboard","description":"提交日报+任务追踪","frequency":"daily"},{"tool":"SOP数据库","path":"/sop-database","description":"查阅岗位SOP","frequency":"daily"},{"tool":"在线测试","path":"/knowledge-compliance","description":"参加理论测试","frequency":"weekly"}]',
 '[{"reportType":"daily","frequency":"每日","to":"直属主管"},{"reportType":"weekly","frequency":"每周五","to":"部门经理"}]',
 '基础扎实的工程师，走得更远。每一步都算数。',
 '🔨 Foundation Built', '基础筑成者', 4),

('G5', '首月里程碑', 'First Milestone', '你已经迈出了坚实的第一步', 'Flag', '#22c55e',
 1, 1,
 '入职满1个月，第一次正式回顾与评估。总结所学、查找差距、设定下阶段目标。',
 '一个月了！还记得第一天的忐忑吗？现在的你已经完全不一样了。你知道了5S是什么，你能看懂基本图纸，你开始理解为什么GRT对品质如此严苛。这是值得庆祝的时刻——但旅程才刚开始。',
 '从新人到GRT工程师，你用一个月的时间完成了最重要的转变：从"我来打工"到"我在创造价值"。',
 '每一次回顾都是进步的起点。在GRT，我们不惧怕差距，我们拥抱差距——因为差距就是成长空间。',
 '[{"role":"ALL","objectives":[{"title":"完成首月自我评估","type":"kpi"},{"title":"与主管完成1对1面谈","type":"culture"},{"title":"制定2-3月学习计划","type":"learning"},{"title":"获得首月绩效评分","type":"kpi"}]}]',
 '[{"tool":"高管绩效总览","path":"/executive-review","description":"主管查看月度评估","frequency":"monthly"},{"tool":"员工成长平台","path":"/employee-growth","description":"查看任务质量指标","frequency":"monthly"}]',
 '[{"reportType":"monthly","frequency":"月末","to":"直属主管+HRBP"}]',
 '第一个月，你证明了自己的选择是正确的。第二个月，让我们更加出色。',
 '🏁 First Month', '首月达成者', 5),

('G6', '试用成长', 'Probation Growth', '在挑战中加速成长', 'TrendingUp', '#0ea5e9',
 2, 3,
 '入职2-3个月，试用期冲刺。承担更多独立任务，证明自己的价值。',
 '试用期不是考验期，而是成长加速期。在这两个月里，你将独立完成越来越多的任务，你会遇到困难和挑战——但请记住，每一个GRT工程师都是这样走过来的。你不是一个人在战斗，团队永远是你的后盾。',
 '最有效的资源创造生产力——你就是GRT最宝贵的资源。你的成长速度，决定了GRT的发展速度。',
 '试用期的目标不是"不犯错"，而是"快速学习"。在GRT，我们宽容失误，但不宽容不学习。',
 '[{"role":"ALL","objectives":[{"title":"独立完成3个以上标准任务","type":"project"},{"title":"KPI评分达到合格线","type":"kpi"},{"title":"通过岗位Lv1理论测试","type":"certification"},{"title":"获得1位同事的正面反馈","type":"social"}]}]',
 '[{"tool":"赋能工作台","path":"/personal-dashboard","description":"日报+任务+AI助手","frequency":"daily"},{"tool":"任务驾驶舱","path":"/task-cockpit","description":"任务进度追踪","frequency":"daily"},{"tool":"企业知识合规","path":"/knowledge-compliance","description":"继续深度学习","frequency":"weekly"}]',
 '[{"reportType":"daily","frequency":"每日","to":"直属主管"},{"reportType":"weekly","frequency":"每周","to":"部门经理"},{"reportType":"monthly","frequency":"月末","to":"HRBP"}]',
 '加速成长的秘诀：把每一个任务都当作学习的机会。',
 '📈 Growth Spurt', '加速成长者', 6),

('G7', '转正蜕变', 'Regularization', '正式成为GRT核心力量', 'BadgeCheck', '#10b981',
 3, 3,
 '入职满3个月，试用期结束。通过转正评审，正式成为GRT正式员工。',
 '这一天，你从"新人"蜕变为"战士"。转正不是终点，而是真正旅程的开始。从今天起，你不再需要别人告诉你该做什么——你已经知道GRT的标准，你已经理解品质的意义，你已经准备好承担更大的责任。恭喜你，GRT工程师！',
 '每一位转正的GRT工程师，都是全球最好的工业洁净系统的守护者。这份信任，价值千金。',
 '转正是对你过去3个月努力的认可，更是对你未来无限可能的期许。工程师的精彩人生，从这里真正展开。',
 '[{"role":"ALL","objectives":[{"title":"通过转正评审","type":"certification"},{"title":"完成试用期总结报告","type":"kpi"},{"title":"设定年度个人发展目标","type":"learning"},{"title":"参加转正仪式","type":"culture"}]}]',
 '[{"tool":"我的360画像","path":"/my-360-profile","description":"查看个人能力雷达图","frequency":"monthly"}]',
 '[{"reportType":"quarterly","frequency":"季末","to":"部门经理+总经理"}]',
 '你已经证明了自己。现在，让我们一起证明GRT。',
 '✅ Regularized', '转正成功', 7),

('G8', '独立担当', 'Independence', '独当一面的工程师', 'Shield', '#6366f1',
 3, 6,
 '转正后3-6个月，从"被指导"到"能独立"。独立负责工序/模块/任务，输出稳定可靠的成果。',
 '独立，不是孤军奋战，而是有能力为团队贡献确定性的价值。在这个阶段，你的目标是：让主管放心把任务交给你，让同事信任你的输出质量。这种信任，是工程师最珍贵的勋章。',
 '当你能独立保证一道工序的品质时，你就是那台洁净设备质量链条上不可替代的一环。',
 '独立担当的工程师，是GRT最坚实的基石。我们不需要英雄，我们需要每个岗位上值得信赖的专业人士。',
 '[{"role":"ALL","objectives":[{"title":"独立负责1个完整工序/模块","type":"project"},{"title":"达成月度KPI目标","type":"kpi"},{"title":"完成Lv2必学文档","type":"learning"},{"title":"零重大质量事故","type":"kpi"},{"title":"能指导新入职同事","type":"leadership"}]}]',
 '[{"tool":"赋能工作台","path":"/personal-dashboard","description":"日常工作管理","frequency":"daily"},{"tool":"任务驾驶舱","path":"/task-cockpit","description":"独立任务追踪","frequency":"daily"},{"tool":"高管绩效总览","path":"/executive-review","description":"主管绩效查阅","frequency":"monthly"}]',
 '[{"reportType":"daily","frequency":"每日","to":"直属主管"},{"reportType":"weekly","frequency":"每周","to":"部门经理"},{"reportType":"monthly","frequency":"月末","to":"部门经理"}]',
 '能被信任的人，才能被委以重任。你正在赢得这份信任。',
 '🛡️ Independent', '独立担当者', 8),

('G9', '专业深耕', 'Professional Deepening', '从合格走向优秀', 'Microscope', '#7c3aed',
 6, 12,
 '入职6-12个月，深入专业领域。参与FMEA、掌握SPC、理解客户要求、优化工艺参数。',
 '如果说前6个月你在学习"怎么做"，那么从现在开始，你要学习"为什么这样做"和"怎么做得更好"。理解背后的原理，你就不再是操作员，而是真正的工程师。GRT的工程师文化，就是鼓励每个人思考、质疑、改善。',
 '优秀的工程师不只是执行标准，更是理解标准、改善标准。这就是GRT能持续做到全球最好的秘密。',
 '深耕专业的过程可能枯燥，但每一次深入都让你离"专家"更近一步。在GRT，专业是最受尊重的品质。',
 '[{"role":"ALL","objectives":[{"title":"通过IATF 16949基础测试","type":"certification","linkedCategoryCode":"QUALITY"},{"title":"参与1次FMEA分析","type":"project"},{"title":"完成Lv2全部学习内容","type":"learning"},{"title":"提出1个改善提案","type":"innovation"},{"title":"KPI稳定在合格线以上","type":"kpi"}]}]',
 '[{"tool":"企业知识合规","path":"/knowledge-compliance","description":"Lv2-3深度学习","frequency":"weekly"},{"tool":"OEE设备效率","path":"/shop-floor/oee-dashboard","description":"产线效率分析","frequency":"weekly"},{"tool":"品质工作台","path":"/quality-workbench","description":"FMEA/SPC工具","frequency":"as_needed"}]',
 '[{"reportType":"daily","frequency":"每日","to":"直属主管"},{"reportType":"monthly","frequency":"月末","to":"部门经理"},{"reportType":"quarterly","frequency":"季末","to":"部门经理+总经理"}]',
 '深耕的价值不在于速度，而在于深度。慢慢来，比较快。',
 '🔬 Deep Expert', '专业深耕者', 9),

('G10', '年度复盘', 'Annual Review', '一年了，看看你走了多远', 'CalendarCheck', '#f97316',
 12, 12,
 '入职满1年。全面复盘年度成长：KPI、能力、项目、培训、文化贡献。设定Lv3+发展路径。',
 '365天前，你还是那个对GRT充满好奇的新人。今天，你已经是一位能独立工作的GRT工程师。回头看看这一年：你学会了多少技能？你完成了多少任务？你为多少台洁净设备贡献了品质？这些数字背后，是你的汗水和成长。',
 '一年间，你已经真切地感受到：做全球最好的工业洁净系统，不是一个人的事，而是每一个GRT人日复一日的坚持。',
 '年度复盘不是考试，而是庆典——庆祝你的成长，也为下一年的飞跃做准备。',
 '[{"role":"ALL","objectives":[{"title":"完成年度自我评估报告","type":"kpi"},{"title":"获得年度综合评级","type":"kpi"},{"title":"制定下年度个人发展计划","type":"learning"},{"title":"参加年度表彰大会","type":"culture"},{"title":"完成360°反馈","type":"social"}]}]',
 '[{"tool":"高管绩效总览","path":"/executive-review","description":"年度绩效全景","frequency":"annual"},{"tool":"战力排行榜","path":"/arena/showcase","description":"查看年度排名","frequency":"annual"}]',
 '[{"reportType":"annual","frequency":"年末","to":"部门经理+总经理+董事长"}]',
 '一年的坚持，换来一年的成长。下一年，让我们走得更远、飞得更高。',
 '📅 Year One', '年度里程碑', 10),

('G11', '能力跃升', 'Capability Leap', '突破瓶颈，能力跃迁', 'Zap', '#eab308', 12, 24,
 '1-2年，从"合格"到"优秀"的关键跃升期。突破舒适区，挑战更高难度的任务和项目。',
 '这个阶段你会遇到"瓶颈"——觉得自己什么都会了，但又似乎缺少什么。这正是跃升的前奏。突破它，你就进入了新的境界。',
 '跃升不是线性的，而是台阶式的。每一次突破瓶颈，都让GRT的整体能力上一个台阶。',
 '舒适区是成长的敌人。在GRT，我们鼓励每个人主动走出舒适区，去挑战不可能。',
 '[{"role":"ALL","objectives":[{"title":"主导1个完整项目/模块","type":"project"},{"title":"达到Lv3技能等级","type":"certification"},{"title":"培养1名新同事","type":"leadership"},{"title":"KPI排名前50%","type":"kpi"}]}]',
 '[]', '[]', '瓶颈是通往卓越的必经之路。跨过去，你就是不一样的自己。', '⚡ Leap', '能力跃升者', 11),

('G12', '项目引领', 'Project Leadership', '从执行者到引领者', 'Compass', '#0284c7', 24, 36,
 '2-3年，开始主导项目或关键模块。从"做好自己的事"到"带领团队做成事"。',
 '当你开始负责一个项目时，你的视野会发生根本性的变化。你不再只关心自己的工序，而是关注整个链条。这就是GRT工程师的成长——从点到线，从线到面。',
 '每一个项目的成功交付，都是GRT"做全球最好"承诺的具体兑现。你是这份承诺的执行者和守护者。',
 '引领不是命令，而是以身作则。最好的项目经理，就是最好的工程师。',
 '[{"role":"ALL","objectives":[{"title":"主导1个完整项目","type":"project"},{"title":"项目按时按质交付","type":"kpi"},{"title":"团队成员满意度≥80%","type":"social"},{"title":"编写1份技术总结/改善报告","type":"learning"}]}]',
 '[]', '[]', '从执行到引领，是工程师最关键的蜕变。你准备好了吗？', '🧭 Leader', '项目引领者', 12),

('G13', '团队赋能', 'Team Empowerment', '让身边的人因你而更强', 'Users', '#10b981', 24, 36,
 '2-3年，不仅自己强，还要让团队强。分享知识、培养后辈、建立标准。',
 '一个人走得快，一群人走得远。在GRT，最受尊敬的不是最厉害的"独行侠"，而是能让整个团队变强的"赋能者"。当你开始写培训资料、带徒弟、建立SOP时，你的价值已经超越了个人。',
 '做全球最好，不能只靠几个人。GRT的壁垒，是每一位工程师的集体能力。',
 '教是最好的学。当你能把自己会的教给别人时，你就真正掌握了它。',
 '[{"role":"ALL","objectives":[{"title":"培养2名后辈达到独立水平","type":"leadership"},{"title":"编写或更新1份SOP/指导书","type":"learning"},{"title":"在团队内部分享1次技术经验","type":"social"},{"title":"获得团队成员的感谢或认可","type":"social"}]}]',
 '[]', '[]', '你的价值，在于让更多人变得有价值。', '👥 Enabler', '团队赋能者', 13),

('G14', '专家之路', 'Expert Path', '成为领域内不可替代的专家', 'Brain', '#a855f7', 36, 60,
 '3-5年，在特定领域达到专家级别。能解决复杂问题，能做技术决策，能代表GRT面对客户。',
 '专家不是一个头衔，而是一种状态——当团队遇到最困难的问题时，大家第一个想到的就是你。在GRT，专家不是高高在上的，而是最能解决实际问题的人。',
 '全球最好的洁净系统，需要全球最好的专家团队。你，就是其中之一。',
 '专家的真正标志不是知道多少，而是能解决多少别人解决不了的问题。',
 '[{"role":"ALL","objectives":[{"title":"解决3个以上复杂技术问题","type":"project"},{"title":"达到Lv4技能等级","type":"certification"},{"title":"代表公司参加1次客户审核","type":"project"},{"title":"获得六西格玛绿带","type":"certification"},{"title":"年度KPI排名前30%","type":"kpi"}]}]',
 '[]', '[]', '专家之路没有终点，只有更高的山峰等你攀登。', '🧠 Expert', '领域专家', 14),

('G15', '跨域协同', 'Cross-Domain', '打破边界，创造更大价值', 'Network', '#06b6d4', 36, 60,
 '3-5年，跨越部门和专业的边界。参与跨部门项目，理解全局，创造协同价值。',
 '最伟大的创新，往往发生在学科的交叉点。当你开始理解其他部门的工作时，你会发现无数的改善机会。在GRT，我们鼓励打破"部门墙"，因为客户看到的永远是GRT整体。',
 '洁净系统是机械、电气、控制、软件的完美协同。跨域协同的你，就是这种协同的缩影。',
 '视野决定境界。当你能站在全局视角看问题时，你已经超越了90%的人。',
 '[{"role":"ALL","objectives":[{"title":"参与1个跨部门项目","type":"project"},{"title":"与其他部门完成1次知识共享","type":"social"},{"title":"提出1个跨部门改善方案","type":"innovation"}]}]',
 '[]', '[]', '打破边界的人，创造了最大的价值。', '🌐 Connector', '跨域连接者', 15),

('G16', '战略视野', 'Strategic Vision', '从战术到战略，视野决定高度', 'Telescope', '#1e40af', 60, 84,
 '5年以上，开始参与战略层面的思考和决策。从"做事"到"做局"的思维转变。',
 '当你在GRT超过5年，你已经不只是一个执行者，而是这个行业的资深从业者。你的每一个建议和判断，都基于丰富的实践经验。现在，是时候把这些经验升华为战略洞察了。',
 '做全球最好，需要最具远见的战略。而最好的战略，来自最了解一线的人。',
 '战略不是空中楼阁，而是基于深厚实践的前瞻判断。GRT的战略，由像你这样的人共同塑造。',
 '[{"role":"ALL","objectives":[{"title":"参与部门年度战略规划","type":"leadership"},{"title":"提出1个前瞻性技术/市场提案","type":"innovation"},{"title":"达到Lv5或接近大师水平","type":"certification"}]}]',
 '[]', '[]', '站得越高，看得越远。你的视野，就是GRT的视野。', '🔭 Visionary', '战略远见者', 16),

('G17', '导师传承', 'Mentorship Legacy', '你的经验是GRT最珍贵的财富', 'BookHeart', '#dc2626', 60, 84,
 '5年以上，成为正式导师。把毕生所学传递给下一代GRT工程师。',
 '还记得你刚入职时那位耐心指导你的前辈吗？现在，你就是那个前辈。你的一句话，可能改变一个年轻工程师的职业轨迹。在GRT，我们相信：知识的传承，比个人的成就更伟大。',
 '全球最好的洁净系统的秘密，不在图纸里，而在工程师的心里。传承，就是把这个秘密传递下去。',
 '最伟大的工程师，不是自己最厉害的那个人，而是培养出最多优秀工程师的人。',
 '[{"role":"ALL","objectives":[{"title":"正式带教2名徒弟","type":"leadership"},{"title":"编写1份行业级知识文档","type":"learning"},{"title":"在公司层面做1次技术分享","type":"social"},{"title":"建立1个可传承的知识体系","type":"learning"}]}]',
 '[]', '[]', '传承是最高形式的创造。你的智慧，将在GRT生生不息。', '📖 Mentor', '传承导师', 17),

('G18', '行业影响', 'Industry Impact', '不只代表GRT，更代表行业', 'Globe', '#059669', 84, 120,
 '7年以上，在行业层面产生影响力。参与行业标准制定、技术交流、产学研合作。',
 '当行业同仁提起工业洁净系统时，他们会提到GRT——而你，就是GRT的代言人。你的专业水准，代表着中国工业洁净系统的最高水平。这是一份荣耀，也是一份责任。',
 '"做全球最好"不只是GRT的目标，更是中国制造业的追求。你在行业中的每一次发言，都在推动这个目标。',
 '行业影响力是靠实力赢来的尊重。GRT工程师，在任何舞台上都有底气。',
 '[{"role":"ALL","objectives":[{"title":"参与1项行业标准或规范制定","type":"innovation"},{"title":"在行业论坛/展会上做技术分享","type":"social"},{"title":"发表1篇专利或技术论文","type":"innovation"}]}]',
 '[]', '[]', '你不仅代表GRT，更代表中国工业洁净技术的未来。', '🌍 Influencer', '行业影响者', 18),

('G19', '荣誉退场', 'Honorable Transition', '带着荣耀，开启新篇章', 'Sunset', '#f59e0b', NULL, NULL,
 '无论因何离开GRT，你的贡献永远铭刻在这里。完善交接、传承知识、留下正面影响。',
 '离开不是结束，而是另一段旅程的开始。在GRT的每一天，都让你成为了更好的自己。带走的不只是经验和技能，还有GRT工程师精神：追求极致、永不满足、持续改善。无论你去哪里，这些品质都会让你发光。',
 '每一位离开的GRT人，都是GRT品牌最好的传播者。你带走的品质标准，会影响你触碰的每一个地方。',
 '感恩每一段旅程。在GRT度过的日子，是你人生中最有价值的投资之一。',
 '[{"role":"ALL","objectives":[{"title":"完成全部工作交接","type":"project"},{"title":"知识文档归档与传承","type":"learning"},{"title":"完成离职面谈","type":"culture"},{"title":"加入GRT校友网络","type":"social"}]}]',
 '[]', '[]', '带着GRT工程师的骄傲，去征服更广阔的世界。', '🌅 Honored', '荣誉校友', 19),

('G20', '校友生态', 'Alumni Network', '一日GRT人，终身GRT人', 'Link', '#6b7280', NULL, NULL,
 '离开GRT后，你仍是GRT大家庭的一员。保持联系、分享近况、参与校友活动。',
 'GRT不只是一份工作，而是一段人生经历。离开的人，我们称之为"校友"。GRT校友遍布全球工业洁净领域，彼此支持、互通有无。也许有一天，你会带着更丰富的经历重新回到GRT——我们永远为你留一盏灯。',
 'GRT校友网络，是全球工业洁净行业最有影响力的人脉圈。因为我们共同追求的，是"做全球最好"。',
 '一日工程师，终身工程师。GRT精神，是你终身的印记。',
 '[{"role":"ALL","objectives":[{"title":"保持校友资料更新","type":"social"},{"title":"参与年度校友聚会","type":"culture"},{"title":"为GRT推荐优秀人才","type":"social"}]}]',
 '[]', '[]', '欢迎回家。GRT永远为你敞开大门。', '🔗 Alumni', '永恒校友', 20);
