import mysql from 'mysql2/promise';
import dotenv from 'dotenv';
dotenv.config();

const connection = await mysql.createConnection(process.env.DATABASE_URL);

const tables = [
  `CREATE TABLE IF NOT EXISTS engineering_tasks (
    id int AUTO_INCREMENT PRIMARY KEY,
    taskId varchar(50) NOT NULL UNIQUE,
    projectId int NOT NULL,
    phaseCode varchar(10) NOT NULL,
    taskType varchar(50) NOT NULL,
    taskName varchar(200) NOT NULL,
    taskDescription text,
    primaryAssigneeId int,
    backupAssigneeId int,
    supervisorId int,
    plannedStartDate date,
    plannedEndDate date,
    actualStartDate date,
    actualEndDate date,
    status enum('pending', 'in_progress', 'completed', 'on_hold', 'cancelled') DEFAULT 'pending',
    priority enum('urgent', 'high', 'medium', 'low') DEFAULT 'medium',
    progress int DEFAULT 0,
    bomItemId int,
    createdAt timestamp DEFAULT CURRENT_TIMESTAMP,
    updatedAt timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS task_notifications (
    id int AUTO_INCREMENT PRIMARY KEY,
    notificationId varchar(50) NOT NULL UNIQUE,
    taskId varchar(50) NOT NULL,
    recipientId int NOT NULL,
    channel enum('screen_popup', 'system_message', 'email', 'wechat', 'sms') NOT NULL,
    subject varchar(200),
    content text,
    priority enum('urgent', 'high', 'medium', 'low') DEFAULT 'medium',
    scheduledAt timestamp NULL,
    sentAt timestamp NULL,
    confirmationRequired boolean DEFAULT false,
    confirmationDeadline timestamp NULL,
    confirmedAt timestamp NULL,
    confirmedBy int,
    status enum('pending', 'scheduled', 'sent', 'delivered', 'confirmed', 'failed') DEFAULT 'pending',
    retryCount int DEFAULT 0,
    lastError text,
    createdAt timestamp DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS customer_communications (
    id int AUTO_INCREMENT PRIMARY KEY,
    communicationId varchar(50) NOT NULL UNIQUE,
    projectId int NOT NULL,
    phaseCode varchar(10),
    communicationType varchar(50),
    subject varchar(200),
    summary text,
    actionItems text,
    customerContacts text,
    internalParticipants text,
    communicationDate timestamp NULL,
    nextFollowUp date,
    aiSummary text,
    aiNextActions text,
    aiGeneratedAt timestamp NULL,
    createdAt timestamp DEFAULT CURRENT_TIMESTAMP,
    createdBy int
  )`,
  `CREATE TABLE IF NOT EXISTS engineering_inputs (
    id int AUTO_INCREMENT PRIMARY KEY,
    inputId varchar(50) NOT NULL UNIQUE,
    projectId int NOT NULL,
    sourceType varchar(50) NOT NULL,
    sourceId varchar(50),
    inputCategory varchar(50),
    inputContent text,
    importance enum('critical', 'high', 'medium', 'low') DEFAULT 'medium',
    aiProcessed boolean DEFAULT false,
    aiExtractedRequirements text,
    aiSuggestedTasks text,
    aiProcessedAt timestamp NULL,
    distributedTo text,
    distributionStatus varchar(20),
    createdAt timestamp DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS bom_assembly_tasks (
    id int AUTO_INCREMENT PRIMARY KEY,
    taskId varchar(50) NOT NULL UNIQUE,
    bomItemId int NOT NULL,
    bomItemName varchar(200),
    bomLevel int DEFAULT 1,
    assemblyType enum('mechanical', 'electrical', 'pneumatic', 'hydraulic') NOT NULL,
    workstation varchar(50),
    estimatedHours decimal(6,2),
    actualHours decimal(6,2),
    primaryAssigneeId int,
    backupAssigneeId int,
    supervisorId int,
    selfCheck boolean DEFAULT false,
    mutualCheck boolean DEFAULT false,
    specialCheck boolean DEFAULT false,
    assemblyInstruction varchar(500),
    qualityStandard varchar(500),
    safetyProcedure varchar(500),
    status enum('pending', 'in_progress', 'completed', 'rework') DEFAULT 'pending',
    createdAt timestamp DEFAULT CURRENT_TIMESTAMP,
    updatedAt timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS smart_devices (
    id int AUTO_INCREMENT PRIMARY KEY,
    deviceId varchar(50) NOT NULL UNIQUE,
    deviceType enum('humanoid_robot', 'agv', 'inspection_system', 'cnc_machine', 'assembly_robot', 'vision_system', 'sensor_array') NOT NULL,
    deviceName varchar(100) NOT NULL,
    manufacturer varchar(100),
    model varchar(100),
    protocol enum('rest', 'grpc', 'mqtt', 'opc_ua', 'modbus') NOT NULL,
    endpoint varchar(500),
    credentialsEncrypted text,
    capabilities text,
    status enum('online', 'offline', 'error', 'maintenance') DEFAULT 'offline',
    lastHeartbeat timestamp NULL,
    createdAt timestamp DEFAULT CURRENT_TIMESTAMP,
    updatedAt timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS device_tasks (
    id int AUTO_INCREMENT PRIMARY KEY,
    deviceTaskId varchar(50) NOT NULL UNIQUE,
    deviceId varchar(50) NOT NULL,
    taskType varchar(50) NOT NULL,
    taskData text,
    projectId int,
    bomItemId int,
    engineeringTaskId varchar(50),
    status enum('pending', 'queued', 'running', 'completed', 'failed', 'cancelled') DEFAULT 'pending',
    progress int DEFAULT 0,
    result text,
    errorMessage text,
    scheduledAt timestamp NULL,
    startedAt timestamp NULL,
    completedAt timestamp NULL,
    createdAt timestamp DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS cad_models (
    id int AUTO_INCREMENT PRIMARY KEY,
    modelId varchar(50) NOT NULL UNIQUE,
    modelName varchar(200) NOT NULL,
    modelType varchar(50),
    originalFormat varchar(20),
    originalFileUrl varchar(500),
    stepFileUrl varchar(500),
    gltfFileUrl varchar(500),
    urdfFileUrl varchar(500),
    assemblyTree text,
    features text,
    dimensions text,
    materials text,
    graspPoints text,
    assemblySequence text,
    equipmentModelId int,
    bomHeaderId int,
    createdAt timestamp DEFAULT CURRENT_TIMESTAMP,
    updatedAt timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS customer_ai_connections (
    id int AUTO_INCREMENT PRIMARY KEY,
    connectionId varchar(50) NOT NULL UNIQUE,
    customerId int NOT NULL,
    connectionName varchar(100),
    apiEndpoint varchar(500),
    authType varchar(20),
    credentialsEncrypted text,
    syncEnabled boolean DEFAULT false,
    syncIntervalMinutes int DEFAULT 60,
    syncDataTypes text,
    status enum('active', 'inactive', 'error') DEFAULT 'inactive',
    lastSyncAt timestamp NULL,
    lastError text,
    createdAt timestamp DEFAULT CURRENT_TIMESTAMP,
    updatedAt timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS customer_portal_accounts (
    id int AUTO_INCREMENT PRIMARY KEY,
    accountId varchar(50) NOT NULL UNIQUE,
    customerId int NOT NULL,
    accountType enum('standard', 'premium', 'enterprise') DEFAULT 'standard',
    companyName varchar(200),
    contactEmail varchar(100),
    status enum('active', 'suspended', 'inactive') DEFAULT 'active',
    createdAt timestamp DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS customer_portal_users (
    id int AUTO_INCREMENT PRIMARY KEY,
    portalUserId varchar(50) NOT NULL UNIQUE,
    accountId varchar(50) NOT NULL,
    email varchar(100) NOT NULL,
    name varchar(100),
    role varchar(50),
    passwordHash varchar(255),
    lastLogin timestamp NULL,
    status enum('active', 'suspended', 'inactive') DEFAULT 'active',
    createdAt timestamp DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS project_access_permissions (
    id int AUTO_INCREMENT PRIMARY KEY,
    permissionId varchar(50) NOT NULL UNIQUE,
    accountId varchar(50) NOT NULL,
    projectId int NOT NULL,
    accessLevel enum('view', 'interact', 'full') DEFAULT 'view',
    allowedModules text,
    dataScope text,
    grantedAt timestamp DEFAULT CURRENT_TIMESTAMP,
    expiresAt timestamp NULL,
    grantedBy int
  )`,
  `CREATE TABLE IF NOT EXISTS special_approvals (
    id int AUTO_INCREMENT PRIMARY KEY,
    approvalId varchar(50) NOT NULL UNIQUE,
    accountId varchar(50) NOT NULL,
    approvalType varchar(50) NOT NULL,
    approvalScope text,
    conditions text,
    requestedAt timestamp DEFAULT CURRENT_TIMESTAMP,
    requestedBy int,
    approvedAt timestamp NULL,
    approvedBy int,
    expiresAt timestamp NULL,
    status enum('pending', 'approved', 'rejected', 'expired') DEFAULT 'pending'
  )`,
  `CREATE TABLE IF NOT EXISTS customer_access_logs (
    id int AUTO_INCREMENT PRIMARY KEY,
    logId varchar(50) NOT NULL UNIQUE,
    portalUserId varchar(50) NOT NULL,
    action varchar(100),
    resourceType varchar(50),
    resourceId varchar(50),
    ipAddress varchar(45),
    userAgent text,
    requestData text,
    createdAt timestamp DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS seo_configurations (
    id int AUTO_INCREMENT PRIMARY KEY,
    seoId varchar(50) NOT NULL UNIQUE,
    pageType varchar(50) NOT NULL,
    pageId varchar(50),
    title varchar(200),
    description varchar(500),
    keywords text,
    canonicalUrl varchar(500),
    ogTitle varchar(200),
    ogDescription varchar(500),
    ogImage varchar(500),
    structuredData text,
    status enum('active', 'inactive') DEFAULT 'active',
    updatedAt timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  )`
];

for (const sql of tables) {
  try {
    await connection.execute(sql);
    const tableName = sql.match(/CREATE TABLE IF NOT EXISTS (\w+)/)[1];
    console.log(`✅ Created table: ${tableName}`);
  } catch (err) {
    console.error(`❌ Error: ${err.message}`);
  }
}

await connection.end();
console.log('\nDone!');
