/**
 * CEO Smart Motivation Command Schema
 *
 * CEO主动激励指挥系统 — 5张核心表:
 * 1. smart_task_assignments — 智能任务分配
 * 2. employee_state_signals — 员工状态信号（UWB到位/情绪/专注度）
 * 3. kpi_proactive_alerts — KPI前瞻性预警
 * 4. motivation_moments — 激励时刻记录
 * 5. technical_assist_sessions — 技术攻关协助会话
 */

import { pgTable, serial, integer, varchar, text, timestamp, boolean, decimal, index, json } from 'drizzle-orm/pg-core';
import type { InferSelectModel, InferInsertModel } from 'drizzle-orm';

// ============================================
// 1. 智能任务分配 (Smart Task Assignments)
// ============================================
export const smartTaskAssignments = pgTable('smart_task_assignments', {
  id: serial().primaryKey(),
  taskTitle: varchar({ length: 300 }).notNull(),
  taskDescription: text(),
  challengeLevel: varchar({ length: 20 }).default('normal'), // easy/normal/challenging/stretch
  assignedTo: integer().notNull(),
  assignedToName: varchar({ length: 100 }),
  assignedBy: integer().notNull(),
  assignedByName: varchar({ length: 100 }),
  projectId: integer(),
  processCode: varchar({ length: 20 }),
  estimatedHours: decimal({ precision: 8, scale: 2 }),
  deadlineAt: timestamp({ mode: 'string' }),
  status: varchar({ length: 20 }).default('pending'), // pending/accepted/in_progress/blocked/completed/exceeded
  priorityScore: integer().default(5), // 1-10
  motivationalNote: text(), // 激励提示词
  technicalHints: text(), // 技术提示/思考方向
  collaboratorIds: json(), // 协作人员IDs
  scheduledPushTime: timestamp({ mode: 'string' }), // 预约推送时间
  flashAnnotation: text(), // 闪烁附注内容
  flashUntilAcknowledged: boolean().default(true),
  acknowledgedAt: timestamp({ mode: 'string' }),
  employeeStateRequired: varchar({ length: 30 }), // seated/focused/post_meeting/morning_arrival
  kpiImpactArea: varchar({ length: 100 }), // 关联KPI领域
  kpiBoostPoints: integer().default(0), // 完成后KPI加分
  completedAt: timestamp({ mode: 'string' }),
  completionQuality: varchar({ length: 20 }), // outstanding/good/acceptable/needs_improvement
  ceoFeedback: text(),
  createdAt: timestamp({ mode: 'string' }).defaultNow(),
  updatedAt: timestamp({ mode: 'string' }).defaultNow(),
}, (table) => [
  index('sta_assigned_to_idx').on(table.assignedTo),
  index('sta_assigned_by_idx').on(table.assignedBy),
  index('sta_status_idx').on(table.status),
  index('sta_priority_score_idx').on(table.priorityScore),
  index('sta_scheduled_push_time_idx').on(table.scheduledPushTime),
  index('sta_challenge_level_idx').on(table.challengeLevel),
]);

// ============================================
// 2. 员工状态信号 (Employee State Signals)
// ============================================
export const employeeStateSignals = pgTable('employee_state_signals', {
  id: serial().primaryKey(),
  employeeId: integer().notNull(),
  signalType: varchar({ length: 30 }).notNull(), // seated/arrived/focused/in_meeting/break/left/high_energy/low_energy/post_achievement
  detectedAt: timestamp({ mode: 'string' }).defaultNow(),
  source: varchar({ length: 20 }).default('uwb'), // uwb/manual/calendar/system
  zoneId: varchar({ length: 50 }),
  stationId: integer(),
  confidence: decimal({ precision: 3, scale: 2 }).default('1.0'),
  metadata: json(), // 附加数据如UWB坐标/会议标题
  expiresAt: timestamp({ mode: 'string' }),
  createdAt: timestamp({ mode: 'string' }).defaultNow(),
}, (table) => [
  index('ess_employee_id_idx').on(table.employeeId),
  index('ess_signal_type_idx').on(table.signalType),
  index('ess_detected_at_idx').on(table.detectedAt),
  index('ess_employee_signal_idx').on(table.employeeId, table.signalType),
]);

// ============================================
// 3. KPI前瞻性预警 (KPI Proactive Alerts)
// ============================================
export const kpiProactiveAlerts = pgTable('kpi_proactive_alerts', {
  id: serial().primaryKey(),
  employeeId: integer(),
  employeeName: varchar({ length: 100 }),
  departmentId: varchar({ length: 50 }),
  kpiDomain: varchar({ length: 100 }).notNull(), // quality/delivery/cost/efficiency/innovation/collaboration
  currentValue: decimal({ precision: 10, scale: 2 }),
  targetValue: decimal({ precision: 10, scale: 2 }),
  predictedValue: decimal({ precision: 10, scale: 2 }), // AI预测月底值
  trendDirection: varchar({ length: 10 }), // improving/stable/declining/critical
  riskLevel: varchar({ length: 20 }).default('normal'), // normal/watch/warning/critical
  alertMessage: text().notNull(),
  suggestedAction: text(),
  suggestedTaskId: integer(), // 建议的任务ID
  acknowledgedBy: integer(),
  acknowledgedAt: timestamp({ mode: 'string' }),
  autoGeneratedTask: boolean().default(false),
  periodStart: varchar({ length: 10 }),
  periodEnd: varchar({ length: 10 }),
  calculatedAt: timestamp({ mode: 'string' }).defaultNow(),
  createdAt: timestamp({ mode: 'string' }).defaultNow(),
}, (table) => [
  index('kpa_employee_id_idx').on(table.employeeId),
  index('kpa_kpi_domain_idx').on(table.kpiDomain),
  index('kpa_risk_level_idx').on(table.riskLevel),
  index('kpa_trend_direction_idx').on(table.trendDirection),
  index('kpa_calculated_at_idx').on(table.calculatedAt),
]);

// ============================================
// 4. 激励时刻记录 (Motivation Moments)
// ============================================
export const motivationMoments = pgTable('motivation_moments', {
  id: serial().primaryKey(),
  employeeId: integer().notNull(),
  employeeName: varchar({ length: 100 }),
  momentType: varchar({ length: 30 }).notNull(), // challenge_accepted/stretch_completed/kpi_exceeded/peer_recognized/streak_maintained/breakthrough/first_of_kind
  triggerEvent: text().notNull(),
  ceoMessage: text(), // CEO个人化激励语
  deliveryMethod: varchar({ length: 20 }).default('in_app'), // in_app/flash_annotation/team_broadcast/one_on_one
  deliveredAt: timestamp({ mode: 'string' }),
  employeeReaction: varchar({ length: 20 }), // inspired/grateful/motivated/neutral
  reactionNote: text(),
  kpiBoostAwarded: integer().default(0),
  pointsAwarded: integer().default(0),
  visibility: varchar({ length: 20 }).default('private'), // private/team/department/company
  createdBy: integer(),
  createdAt: timestamp({ mode: 'string' }).defaultNow(),
}, (table) => [
  index('mm_employee_id_idx').on(table.employeeId),
  index('mm_moment_type_idx').on(table.momentType),
  index('mm_delivered_at_idx').on(table.deliveredAt),
  index('mm_visibility_idx').on(table.visibility),
]);

// ============================================
// 5. 技术攻关协助会话 (Technical Assist Sessions)
// ============================================
export const technicalAssistSessions = pgTable('technical_assist_sessions', {
  id: serial().primaryKey(),
  requestTitle: varchar({ length: 300 }).notNull(),
  requestDescription: text(),
  requestedBy: integer().notNull(),
  requestedByName: varchar({ length: 100 }),
  projectId: integer(),
  processCode: varchar({ length: 20 }),
  difficultyLevel: varchar({ length: 20 }).default('hard'), // moderate/hard/extreme/breakthrough
  status: varchar({ length: 20 }).default('open'), // open/analyzing/scheduled/in_progress/resolved/escalated
  analysisTools: json(), // 分析手段列表: [{tool, description, url}]
  suggestedExperts: json(), // 建议专家: [{employeeId, name, expertise, availability}]
  scheduledAt: timestamp({ mode: 'string' }),
  meetingLink: varchar({ length: 500 }),
  resolution: text(),
  resolutionAttachments: json(),
  resolvedBy: integer(),
  resolvedByName: varchar({ length: 100 }),
  timeToResolutionHours: decimal({ precision: 8, scale: 2 }),
  lessonsLearned: text(),
  knowledgeBaseLinked: boolean().default(false),
  createdAt: timestamp({ mode: 'string' }).defaultNow(),
  updatedAt: timestamp({ mode: 'string' }).defaultNow(),
}, (table) => [
  index('tas_requested_by_idx').on(table.requestedBy),
  index('tas_status_idx').on(table.status),
  index('tas_difficulty_level_idx').on(table.difficultyLevel),
  index('tas_project_id_idx').on(table.projectId),
  index('tas_scheduled_at_idx').on(table.scheduledAt),
]);

// ============================================
// Type Exports
// ============================================
export type SmartTaskAssignment = InferSelectModel<typeof smartTaskAssignments>;
export type NewSmartTaskAssignment = InferInsertModel<typeof smartTaskAssignments>;

export type EmployeeStateSignal = InferSelectModel<typeof employeeStateSignals>;
export type NewEmployeeStateSignal = InferInsertModel<typeof employeeStateSignals>;

export type KpiProactiveAlert = InferSelectModel<typeof kpiProactiveAlerts>;
export type NewKpiProactiveAlert = InferInsertModel<typeof kpiProactiveAlerts>;

export type MotivationMoment = InferSelectModel<typeof motivationMoments>;
export type NewMotivationMoment = InferInsertModel<typeof motivationMoments>;

export type TechnicalAssistSession = InferSelectModel<typeof technicalAssistSessions>;
export type NewTechnicalAssistSession = InferInsertModel<typeof technicalAssistSessions>;
