/**
 * Inovance (汇川) AM600/H5U PLC Brand Adapter
 *
 * IEC 61131-3 ST, EtherCAT addressing
 * IDE: InoProShop (AM600) / AutoShop (H5U)
 */

import type {
  PlcBrandAdapter, ProgramModuleSpec, MotorSpec, ValveSpec, PidSpec,
  AlarmDef, AccessLevel,
} from "./types";
import { registerAdapter } from "./types";

function genIface(spec: ProgramModuleSpec): string {
  const lines: string[] = [];
  const iface = spec.parameterInterface;
  if (iface.inputs?.length) {
    lines.push("  VAR_INPUT");
    for (const p of iface.inputs) lines.push(`    ${p.name} : ${p.type}; (* ${p.description || ""} *)`);
    lines.push("  END_VAR");
  }
  if (iface.outputs?.length) {
    lines.push("  VAR_OUTPUT");
    for (const p of iface.outputs) lines.push(`    ${p.name} : ${p.type};`);
    lines.push("  END_VAR");
  }
  if (iface.statics?.length) {
    lines.push("  VAR");
    for (const p of iface.statics) lines.push(`    ${p.name} : ${p.type}${p.initialValue ? ` := ${p.initialValue}` : ""};`);
    lines.push("  END_VAR");
  }
  return lines.join("\n");
}

const inovanceAdapter: PlcBrandAdapter = {
  brandKey: "INOVANCE_AM600",
  brandName: "Inovance AM600",
  brandNameZh: "汇川 AM600",
  models: [
    { model: "AM600-CPU1608TP", description: "标准型, 16DI/8DO, EtherCAT", maxIO: 2048 },
    { model: "AM600-CPU1608TN", description: "经济型, 16DI/8DO", maxIO: 1024 },
    { model: "AM600-CPU3202TP", description: "高性能, 32DI/32DO, EtherCAT", maxIO: 4096 },
  ],

  generateVariableDeclaration(name: string, type: string, address?: string): string {
    return address ? `${name} AT ${address} : ${type};` : `${name} : ${type};`;
  },
  generateFBSource(module: ProgramModuleSpec): string {
    return `FUNCTION_BLOCK ${module.moduleName}\n(* ${module.description} *)\n${genIface(module)}\n  (* 实现 *)\nEND_FUNCTION_BLOCK`;
  },
  generateFCSource(module: ProgramModuleSpec): string {
    return `FUNCTION ${module.moduleName} : BOOL\n(* ${module.description} *)\n${genIface(module)}\n  ${module.moduleName} := TRUE;\nEND_FUNCTION`;
  },
  generateOBSource(module: ProgramModuleSpec): string {
    return `PROGRAM ${module.moduleName}\n(* ${module.description} *)\n${genIface(module)}\n  (* 周期执行 *)\nEND_PROGRAM`;
  },
  generateDBSource(module: ProgramModuleSpec): string {
    const fields = module.parameterInterface.statics || [];
    return `TYPE ${module.moduleName}_T :\n  STRUCT\n${fields.map(f => `    ${f.name} : ${f.type};`).join("\n")}\n  END_STRUCT;\nEND_TYPE`;
  },

  formatIOAddress(ioType: string, byteOffset: number, bitOffset?: number): string {
    switch (ioType) {
      case "DI": return `%IX${byteOffset}.${bitOffset ?? 0}`;
      case "DO": return `%QX${byteOffset}.${bitOffset ?? 0}`;
      case "AI": return `%IW${byteOffset}`;
      case "AO": return `%QW${byteOffset}`;
      default: return `%MX${byteOffset}.0`;
    }
  },

  getModeManagerTemplate(stationCount: number): string {
    return [
      `FUNCTION_BLOCK FB_ModeManager`,
      `(* ============================================================`,
      `   7-State Mode Manager — Inovance AM600 / EtherCAT`,
      `   States: 0=INIT, 1=AUTO, 2=MANUAL, 3=SERVICE, 4=CHANGEOVER,`,
      `           5=DEBUG, 6=E_STOP`,
      `   Station count: ${stationCount}`,
      `   ============================================================ *)`,
      ``,
      `  VAR_INPUT`,
      `    modeRequest      : INT;   (* Requested mode 0..6 *)`,
      `    safetyChainOk    : BOOL;  (* Safety chain healthy *)`,
      `    allStationsReady : BOOL;  (* All ${stationCount} stations report ready *)`,
      `    keySwitch        : INT;   (* Physical key position: 0=OFF,1=AUTO,2=MANUAL,3=SERVICE *)`,
      `    enableDebug      : BOOL;  (* HMI debug enable — requires SERVICE key *)`,
      `    changeoverDone   : BOOL;  (* Changeover recipe loaded & confirmed *)`,
      `    resetRequest     : BOOL;  (* Operator reset after E_STOP *)`,
      `  END_VAR`,
      ``,
      `  VAR_OUTPUT`,
      `    currentMode      : INT;   (* Active mode 0..6 *)`,
      `    modeConfirmed    : BOOL;  (* currentMode = modeRequest *)`,
      `    autoRunning      : BOOL;  (* TRUE when fully in AUTO *)`,
      `    faultPresent     : BOOL;  (* Latched fault requiring reset *)`,
      `    modeName         : STRING(20); (* Human-readable state name *)`,
      `  END_VAR`,
      ``,
      `  VAR`,
      `    state            : INT := 0;   (* Internal state variable *)`,
      `    prevState        : INT := -1;  (* Previous state for edge detect *)`,
      `    initTimer        : TON;        (* INIT → ready delay *)`,
      `    entryFlag        : BOOL;       (* One-shot on state entry *)`,
      `    autoHoldTimer    : TON;        (* Minimum hold before AUTO allowed *)`,
      `    stationMask      : DWORD := 0; (* Bitmask of ready stations *)`,
      `    faultLatch       : BOOL := FALSE;`,
      `    exitAuto         : BOOL := FALSE; (* Exit flag for AUTO cleanup *)`,
      `  END_VAR`,
      ``,
      `  (* ---- Safety override: E_STOP has highest priority ---- *)`,
      `  IF NOT safetyChainOk THEN`,
      `    IF state <> 6 THEN`,
      `      prevState := state;  (* Remember where we came from *)`,
      `    END_IF;`,
      `    state := 6;`,
      `    faultLatch := TRUE;`,
      `  END_IF;`,
      ``,
      `  (* ---- Entry / exit edge detection ---- *)`,
      `  entryFlag := (state <> prevState);`,
      `  IF entryFlag THEN`,
      `    prevState := state;`,
      `  END_IF;`,
      ``,
      `  (* ---- Main state machine ---- *)`,
      `  CASE state OF`,
      ``,
      `    (* ---- 0: INIT — power-on self-test ---- *)`,
      `    0:`,
      `      IF entryFlag THEN`,
      `        modeName := 'INIT';`,
      `        autoRunning := FALSE;`,
      `        exitAuto := FALSE;`,
      `        initTimer(IN := FALSE);  (* Reset timer *)`,
      `      END_IF;`,
      ``,
      `      initTimer(IN := TRUE, PT := T#3s);`,
      ``,
      `      (* After 3s, transition based on key switch *)`,
      `      IF initTimer.Q AND safetyChainOk THEN`,
      `        CASE keySwitch OF`,
      `          1: state := 1;  (* AUTO *)`,
      `          2: state := 2;  (* MANUAL *)`,
      `          3: state := 3;  (* SERVICE *)`,
      `        ELSE`,
      `          state := 2;     (* Default to MANUAL if key not set *)`,
      `        END_CASE;`,
      `      END_IF;`,
      ``,
      `    (* ---- 1: AUTO — fully automatic production ---- *)`,
      `    1:`,
      `      IF entryFlag THEN`,
      `        modeName := 'AUTO';`,
      `        autoRunning := FALSE;  (* Not yet confirmed *)`,
      `        autoHoldTimer(IN := FALSE);`,
      `      END_IF;`,
      ``,
      `      (* Require all stations ready before confirming AUTO *)`,
      `      autoHoldTimer(IN := allStationsReady, PT := T#500ms);`,
      `      IF autoHoldTimer.Q THEN`,
      `        autoRunning := TRUE;`,
      `      END_IF;`,
      ``,
      `      (* Transition out of AUTO *)`,
      `      IF modeRequest = 2 AND keySwitch = 2 THEN`,
      `        autoRunning := FALSE;`,
      `        exitAuto := TRUE;`,
      `        state := 2;  (* → MANUAL *)`,
      `      ELSIF modeRequest = 4 THEN`,
      `        autoRunning := FALSE;`,
      `        state := 4;  (* → CHANGEOVER *)`,
      `      ELSIF NOT allStationsReady THEN`,
      `        autoRunning := FALSE;`,
      `        faultLatch := TRUE;`,
      `        state := 2;  (* Fall back to MANUAL on station fault *)`,
      `      END_IF;`,
      ``,
      `    (* ---- 2: MANUAL — operator jog / single-step ---- *)`,
      `    2:`,
      `      IF entryFlag THEN`,
      `        modeName := 'MANUAL';`,
      `        autoRunning := FALSE;`,
      `      END_IF;`,
      ``,
      `      (* Transition to AUTO requires key, safety, and all stations *)`,
      `      IF modeRequest = 1 AND keySwitch = 1 AND safetyChainOk AND allStationsReady THEN`,
      `        state := 1;  (* → AUTO *)`,
      `      ELSIF modeRequest = 3 AND keySwitch = 3 THEN`,
      `        state := 3;  (* → SERVICE *)`,
      `      ELSIF modeRequest = 4 THEN`,
      `        state := 4;  (* → CHANGEOVER *)`,
      `      END_IF;`,
      ``,
      `    (* ---- 3: SERVICE — maintenance access, interlocks relaxed ---- *)`,
      `    3:`,
      `      IF entryFlag THEN`,
      `        modeName := 'SERVICE';`,
      `        autoRunning := FALSE;`,
      `      END_IF;`,
      ``,
      `      (* DEBUG sub-mode requires SERVICE key + HMI enable *)`,
      `      IF enableDebug AND keySwitch = 3 THEN`,
      `        state := 5;  (* → DEBUG *)`,
      `      ELSIF modeRequest = 2 AND keySwitch = 2 THEN`,
      `        state := 2;  (* → MANUAL *)`,
      `      ELSIF modeRequest = 1 AND keySwitch = 1 AND allStationsReady THEN`,
      `        state := 1;  (* → AUTO *)`,
      `      END_IF;`,
      ``,
      `    (* ---- 4: CHANGEOVER — recipe/tool change ---- *)`,
      `    4:`,
      `      IF entryFlag THEN`,
      `        modeName := 'CHANGEOVER';`,
      `        autoRunning := FALSE;`,
      `      END_IF;`,
      ``,
      `      (* Once changeover is confirmed, return to previous mode *)`,
      `      IF changeoverDone THEN`,
      `        IF keySwitch = 1 AND allStationsReady THEN`,
      `          state := 1;  (* → AUTO *)`,
      `        ELSE`,
      `          state := 2;  (* → MANUAL *)`,
      `        END_IF;`,
      `      END_IF;`,
      ``,
      `    (* ---- 5: DEBUG — extended diagnostics, force I/O ---- *)`,
      `    5:`,
      `      IF entryFlag THEN`,
      `        modeName := 'DEBUG';`,
      `        autoRunning := FALSE;`,
      `      END_IF;`,
      ``,
      `      (* Exit DEBUG when key leaves SERVICE position or debug disabled *)`,
      `      IF NOT enableDebug OR keySwitch <> 3 THEN`,
      `        state := 3;  (* → SERVICE *)`,
      `      END_IF;`,
      ``,
      `    (* ---- 6: E_STOP — emergency stop active ---- *)`,
      `    6:`,
      `      IF entryFlag THEN`,
      `        modeName := 'E_STOP';`,
      `        autoRunning := FALSE;`,
      `      END_IF;`,
      ``,
      `      (* Recovery: safety chain restored + operator reset *)`,
      `      IF safetyChainOk AND resetRequest THEN`,
      `        faultLatch := FALSE;`,
      `        state := 0;  (* → INIT — full restart required *)`,
      `      END_IF;`,
      ``,
      `  END_CASE;`,
      ``,
      `  (* ---- Outputs ---- *)`,
      `  currentMode := state;`,
      `  modeConfirmed := (state = modeRequest);`,
      `  faultPresent := faultLatch;`,
      ``,
      `END_FUNCTION_BLOCK`,
    ].join("\n");
  },
  getSafetyTemplate(interlocks: string[], eStopCount: number): string {
    // Generate E-stop input declarations (dual channel per button)
    const eStopInputDecls: string[] = [];
    for (let i = 1; i <= eStopCount; i++) {
      eStopInputDecls.push(
        `    eStop${i}_Ch1 AT %IX${10 + (i - 1) * 2}.0 : BOOL;  (* E-Stop #${i} Channel A — NC contact *)`,
        `    eStop${i}_Ch2 AT %IX${10 + (i - 1) * 2}.1 : BOOL;  (* E-Stop #${i} Channel B — NC contact *)`,
      );
    }
    // Generate interlock input declarations
    const interlockInputDecls = interlocks.map(
      (name, i) => `    ${name} AT %IX${30 + i}.0 : BOOL;  (* Interlock: ${name} — NC contact *)`
    );
    // Dual-channel concordance checks
    const eStopConcordance: string[] = [];
    const eStopChainTerms: string[] = [];
    for (let i = 1; i <= eStopCount; i++) {
      eStopConcordance.push(
        `  eStop${i}_Ok := eStop${i}_Ch1 AND eStop${i}_Ch2;`,
        `  eStop${i}_Discrepancy := eStop${i}_Ch1 XOR eStop${i}_Ch2;`,
        `  (* Discrepancy timer: if channels disagree > 500ms → fault *)`,
        `  eStop${i}_DiscTimer(IN := eStop${i}_Discrepancy, PT := T#500ms);`,
        `  IF eStop${i}_DiscTimer.Q THEN`,
        `    eStop${i}_Ok := FALSE;`,
        `    channelFault := TRUE;`,
        `  END_IF;`,
      );
      eStopChainTerms.push(`eStop${i}_Ok`);
    }
    const interlockChainTerms = interlocks.map(n => `${n}`);
    const allChainTerms = [...eStopChainTerms, "guardDoorOk", ...interlockChainTerms].join(" AND ");
    // Static variable declarations for concordance
    const eStopVarDecls: string[] = [];
    for (let i = 1; i <= eStopCount; i++) {
      eStopVarDecls.push(
        `    eStop${i}_Ok           : BOOL;`,
        `    eStop${i}_Discrepancy  : BOOL;`,
        `    eStop${i}_DiscTimer    : TON;`,
      );
    }

    return [
      `FUNCTION_BLOCK FB_SafetyManager`,
      `(* ============================================================`,
      `   Safety Manager — Inovance AM600 / EtherCAT`,
      `   Dual-channel E-stop, guard door monitoring, EDM feedback,`,
      `   safety relay verification per IEC 13849-1 / ISO 13850`,
      `   E-stop count: ${eStopCount}, Interlocks: ${interlocks.length}`,
      `   ============================================================ *)`,
      ``,
      `  VAR_INPUT`,
      ...eStopInputDecls,
      `    guardDoorClosed AT %IX${20}.0 : BOOL;  (* Guard door closed — NC contact *)`,
      `    guardDoorLock   AT %IX${20}.1 : BOOL;  (* Guard door lock feedback *)`,
      ...interlockInputDecls,
      `    edmFeedback     AT %IX${20}.2 : BOOL;  (* EDM: External Device Monitoring — contactor mirror *)`,
      `    resetButton     AT %IX${20}.3 : BOOL;  (* Manual reset push-button — NO contact *)`,
      `  END_VAR`,
      ``,
      `  VAR_OUTPUT`,
      `    safetyChainOk   : BOOL;  (* Master safety chain — TRUE = all clear *)`,
      `    eStopActive     : BOOL;  (* Any E-stop pressed *)`,
      `    guardDoorOk     : BOOL;  (* Guard door closed AND locked *)`,
      `    edmOk           : BOOL;  (* EDM contactor verified *)`,
      `    channelFault    : BOOL;  (* Dual-channel discrepancy detected *)`,
      `    safetyRelayCmd  AT %QX${40}.0 : BOOL;  (* Command to safety relay K1 *)`,
      `    guardDoorLockCmd AT %QX${40}.1 : BOOL;  (* Solenoid lock command *)`,
      `    faultCode       : INT;   (* 0=OK, 1=EStop, 2=Guard, 3=EDM, 4=Channel, 5=Interlock *)`,
      `  END_VAR`,
      ``,
      `  VAR`,
      ...eStopVarDecls,
      `    eStopChainOk    : BOOL;`,
      `    interlockChainOk: BOOL;`,
      `    edmTimer        : TON;   (* EDM verification window *)`,
      `    edmFaultLatch   : BOOL := FALSE;`,
      `    resetEdge       : R_TRIG;  (* Rising edge on reset button *)`,
      `    relayOffDelay   : TOF;  (* Delayed relay drop-out for clean shutdown *)`,
      `    prevSafetyRelay : BOOL := FALSE;`,
      `  END_VAR`,
      ``,
      `  (* ============================================================`,
      `     STEP 1: Dual-channel E-stop concordance check`,
      `     Each E-stop has two NC contacts (Ch1 + Ch2).`,
      `     Both must agree within 500ms or a channel fault is raised.`,
      `     ============================================================ *)`,
      `  channelFault := FALSE;  (* Re-evaluate each scan *)`,
      ...eStopConcordance,
      ``,
      `  (* Combined E-stop chain *)`,
      `  eStopChainOk := ${eStopChainTerms.length > 0 ? eStopChainTerms.join(" AND ") : "TRUE"};`,
      `  eStopActive := NOT eStopChainOk;`,
      ``,
      `  (* ============================================================`,
      `     STEP 2: Guard door monitoring`,
      `     Door must be closed AND lock feedback confirmed.`,
      `     Lock solenoid energized only when chain is healthy.`,
      `     ============================================================ *)`,
      `  guardDoorOk := guardDoorClosed AND guardDoorLock;`,
      ``,
      `  (* ============================================================`,
      `     STEP 3: Interlock chain`,
      `     All external interlocks must be TRUE (NC wiring = closed).`,
      `     ============================================================ *)`,
      `  interlockChainOk := ${interlockChainTerms.length > 0 ? interlockChainTerms.join(" AND ") : "TRUE"};`,
      ``,
      `  (* ============================================================`,
      `     STEP 4: EDM — External Device Monitoring`,
      `     After safety relay is commanded OFF, the contactor mirror`,
      `     contact (edmFeedback) must open within 300ms.`,
      `     If it stays closed, the contactor is welded → fault.`,
      `     ============================================================ *)`,
      `  IF NOT prevSafetyRelay AND NOT edmFaultLatch THEN`,
      `    (* Safety relay was just turned OFF — start EDM verification *)`,
      `    edmTimer(IN := TRUE, PT := T#300ms);`,
      `    IF edmTimer.Q AND edmFeedback THEN`,
      `      (* Contactor mirror still closed after 300ms → welded contact *)`,
      `      edmFaultLatch := TRUE;`,
      `    END_IF;`,
      `  ELSE`,
      `    edmTimer(IN := FALSE);`,
      `  END_IF;`,
      `  edmOk := NOT edmFaultLatch;`,
      ``,
      `  (* ============================================================`,
      `     STEP 5: Master safety chain evaluation`,
      `     ============================================================ *)`,
      `  safetyChainOk := ${allChainTerms} AND edmOk AND NOT channelFault;`,
      ``,
      `  (* Fault code priority: lower number = higher priority *)`,
      `  IF channelFault THEN`,
      `    faultCode := 4;`,
      `  ELSIF eStopActive THEN`,
      `    faultCode := 1;`,
      `  ELSIF NOT guardDoorOk THEN`,
      `    faultCode := 2;`,
      `  ELSIF NOT edmOk THEN`,
      `    faultCode := 3;`,
      `  ELSIF NOT interlockChainOk THEN`,
      `    faultCode := 5;`,
      `  ELSE`,
      `    faultCode := 0;`,
      `  END_IF;`,
      ``,
      `  (* ============================================================`,
      `     STEP 6: Safety relay and guard door lock outputs`,
      `     ============================================================ *)`,
      `  safetyRelayCmd := safetyChainOk;`,
      `  prevSafetyRelay := safetyRelayCmd;`,
      ``,
      `  (* Guard door lock: energize when safety chain OK (fail-safe = unlocked) *)`,
      `  guardDoorLockCmd := safetyChainOk;`,
      ``,
      `  (* Delayed drop-out: keep relay on for 100ms after chain breaks *)`,
      `  (* to allow orderly shutdown of downstream devices *)`,
      `  relayOffDelay(IN := safetyChainOk, PT := T#100ms);`,
      ``,
      `  (* ============================================================`,
      `     STEP 7: Manual reset logic`,
      `     After fault is cleared (chain restored), operator must press`,
      `     reset button to clear latched faults (EDM, channel).`,
      `     ============================================================ *)`,
      `  resetEdge(CLK := resetButton);`,
      `  IF resetEdge.Q AND eStopChainOk AND guardDoorOk THEN`,
      `    edmFaultLatch := FALSE;`,
      `    channelFault := FALSE;`,
      `  END_IF;`,
      ``,
      `END_FUNCTION_BLOCK`,
    ].join("\n");
  },
  getUserAuthTemplate(levels: AccessLevel[]): string {
    return `FUNCTION_BLOCK FB_UserAuth\n  VAR_INPUT loginReq:BOOL; password:DWORD; level:INT; END_VAR\n  VAR_OUTPUT loggedIn:BOOL; currentLevel:INT; END_VAR\n  VAR pwDB:ARRAY[0..9] OF DWORD; END_VAR\n  IF loginReq AND password=pwDB[level] THEN loggedIn:=TRUE; currentLevel:=level; END_IF;\nEND_FUNCTION_BLOCK`;
  },
  getMotorControlTemplate(motor: MotorSpec): string {
    const isVFD = motor.type === "VFD";
    return [
      `FUNCTION_BLOCK FB_Motor_${motor.name}`,
      `(* ============================================================`,
      `   Motor Control — Inovance AM600 / EtherCAT`,
      `   Motor: ${motor.name}, Power: ${motor.power}kW, Voltage: ${motor.voltage}V`,
      `   Type: ${motor.type}, Station: ${motor.stationCode}`,
      `   Features: VFD ramp control, overload detection with current`,
      `             monitoring, star-delta timing, fault handling,`,
      `             run-hour counter, restart lockout`,
      `   ============================================================ *)`,
      ``,
      `  VAR_INPUT`,
      `    cmdStart       : BOOL;   (* Start command from mode manager *)`,
      `    cmdStop        : BOOL;   (* Stop command *)`,
      `    cmdReset       : BOOL;   (* Fault reset *)`,
      `    safetyOk       : BOOL;   (* Safety chain status *)`,
      `    enableRun      : BOOL;   (* Permissive from upstream logic *)`,
      isVFD ? `    speedRef       : REAL := 50.0; (* VFD speed reference 0..100% *)` : ``,
      isVFD ? `    rampUpTime     : REAL := 5.0;   (* VFD acceleration ramp [s] *)` : ``,
      isVFD ? `    rampDownTime   : REAL := 3.0;   (* VFD deceleration ramp [s] *)` : ``,
      `    overloadLimit  : REAL := ${(motor.power * 1.5).toFixed(1)};  (* Current limit [A] — 150% rated *)`,
      `    overloadDelay  : TIME := T#5s;  (* Overload trip delay *)`,
      `    thermalInput   AT %IW${50} : REAL;  (* Motor winding temperature [°C] *)`,
      `    currentFB      AT %IW${52} : REAL;  (* Current feedback from CT [A] *)`,
      `    motorContactor AT %IX${54}.0 : BOOL;  (* Contactor feedback — mirror contact *)`,
      isVFD ? `    vfdReady       AT %IX${54}.1 : BOOL;  (* VFD ready signal *)` : ``,
      isVFD ? `    vfdFault       AT %IX${54}.2 : BOOL;  (* VFD fault signal *)` : ``,
      `    starDeltaEnable: BOOL := ${isVFD ? "FALSE" : "TRUE"};  (* Enable star-delta starting *)`,
      `    starTime       : TIME := T#3s;   (* Star contactor hold time *)`,
      `  END_VAR`,
      ``,
      `  VAR_OUTPUT`,
      `    motorRunning   : BOOL;   (* Motor confirmed running *)`,
      `    motorFault     : BOOL;   (* Latched fault *)`,
      `    faultCode      : INT;    (* 0=OK,1=Overload,2=Thermal,3=ContactorFail,4=VFD,5=Safety *)`,
      `    contactorCmd   AT %QX${60}.0 : BOOL;  (* Main contactor output *)`,
      isVFD ? `    vfdRunCmd      AT %QX${60}.1 : BOOL;  (* VFD run/enable output *)` : ``,
      isVFD ? `    vfdSpeedOut    AT %QW${62} : REAL;    (* VFD speed command 0..100% *)` : ``,
      `    starContactorCmd AT %QX${60}.2 : BOOL;  (* Star contactor — for star-delta *)`,
      `    deltaContactorCmd AT %QX${60}.3 : BOOL;  (* Delta contactor — for star-delta *)`,
      `    runHours       : REAL;   (* Accumulated run hours *)`,
      `    currentPercent : REAL;   (* Current as % of rated *)`,
      `  END_VAR`,
      ``,
      `  VAR`,
      `    state          : INT := 0;  (* 0=IDLE,1=STARTING,2=STAR,3=STAR_DELTA_TRANS,4=RUNNING,5=STOPPING,6=FAULT *)`,
      `    startEdge      : R_TRIG;`,
      `    resetEdge      : R_TRIG;`,
      `    overloadTimer  : TON;`,
      `    starTimer      : TON;`,
      `    contactorCheckTimer : TON;`,
      isVFD ? `    rampValue      : REAL := 0.0;  (* Current ramp position 0..100% *)` : ``,
      isVFD ? `    rampIncrement  : REAL;          (* Per-scan ramp step *)` : ``,
      isVFD ? `    rampDecrement  : REAL;          (* Per-scan ramp step *)` : ``,
      `    runTimer       : TON;          (* 1-hour accumulator *)`,
      `    restartLockout : TON;          (* Minimum time between restarts *)`,
      `    restartAllowed : BOOL := TRUE;`,
      `    ratedCurrent   : REAL := ${(motor.power * 1000 / (motor.voltage * 1.732 * 0.85)).toFixed(1)}; (* Calculated rated current [A] *)`,
      `    scanTime       : REAL := 0.01; (* 10ms default scan *)`,
      `  END_VAR`,
      ``,
      `  (* ---- Edge detection ---- *)`,
      `  startEdge(CLK := cmdStart);`,
      `  resetEdge(CLK := cmdReset);`,
      ``,
      `  (* ---- Current monitoring (continuous) ---- *)`,
      `  IF ratedCurrent > 0.0 THEN`,
      `    currentPercent := (currentFB / ratedCurrent) * 100.0;`,
      `  ELSE`,
      `    currentPercent := 0.0;`,
      `  END_IF;`,
      ``,
      isVFD ? [
        `  (* ---- VFD ramp increment calculation ---- *)`,
        `  IF rampUpTime > 0.0 THEN`,
        `    rampIncrement := (100.0 / rampUpTime) * scanTime;`,
        `  ELSE`,
        `    rampIncrement := 100.0;`,
        `  END_IF;`,
        `  IF rampDownTime > 0.0 THEN`,
        `    rampDecrement := (100.0 / rampDownTime) * scanTime;`,
        `  ELSE`,
        `    rampDecrement := 100.0;`,
        `  END_IF;`,
      ].join("\n") : ``,
      ``,
      `  (* ---- Safety override ---- *)`,
      `  IF NOT safetyOk THEN`,
      `    state := 6;`,
      `    faultCode := 5;`,
      `  END_IF;`,
      ``,
      `  (* ---- Main state machine ---- *)`,
      `  CASE state OF`,
      ``,
      `    (* 0: IDLE — motor stopped, waiting for start command *)`,
      `    0:`,
      `      contactorCmd := FALSE;`,
      isVFD ? `      vfdRunCmd := FALSE;` : ``,
      isVFD ? `      vfdSpeedOut := 0.0;` : ``,
      isVFD ? `      rampValue := 0.0;` : ``,
      `      starContactorCmd := FALSE;`,
      `      deltaContactorCmd := FALSE;`,
      `      motorRunning := FALSE;`,
      ``,
      `      (* Restart lockout: minimum 10s between stop and next start *)`,
      `      restartLockout(IN := NOT restartAllowed, PT := T#10s);`,
      `      IF restartLockout.Q THEN`,
      `        restartAllowed := TRUE;`,
      `      END_IF;`,
      ``,
      `      IF startEdge.Q AND enableRun AND safetyOk AND NOT motorFault AND restartAllowed THEN`,
      `        state := 1;  (* → STARTING *)`,
      `      END_IF;`,
      ``,
      `    (* 1: STARTING — energize contactor, check feedback *)`,
      `    1:`,
      `      IF starDeltaEnable AND NOT ${isVFD ? "TRUE" : "FALSE"} THEN`,
      `        (* Star-delta start: energize star contactor first *)`,
      `        starContactorCmd := TRUE;`,
      `        deltaContactorCmd := FALSE;`,
      `        contactorCmd := TRUE;`,
      `        state := 2;  (* → STAR phase *)`,
      `      ELSE`,
      `        (* Direct or VFD start *)`,
      `        contactorCmd := TRUE;`,
      isVFD ? `        vfdRunCmd := TRUE;` : ``,
      `        deltaContactorCmd := TRUE;  (* Full winding *)`,
      `        contactorCheckTimer(IN := TRUE, PT := T#2s);`,
      `        IF contactorCheckTimer.Q THEN`,
      `          contactorCheckTimer(IN := FALSE);`,
      `          IF NOT motorContactor THEN`,
      `            (* Contactor did not engage *)`,
      `            faultCode := 3;`,
      `            state := 6;  (* → FAULT *)`,
      `          ELSE`,
      `            state := 4;  (* → RUNNING *)`,
      `          END_IF;`,
      `        END_IF;`,
      `      END_IF;`,
      ``,
      `    (* 2: STAR — star contactor energized, waiting for star timer *)`,
      `    2:`,
      `      starTimer(IN := TRUE, PT := starTime);`,
      `      IF starTimer.Q THEN`,
      `        starTimer(IN := FALSE);`,
      `        state := 3;  (* → STAR-DELTA transition *)`,
      `      END_IF;`,
      ``,
      `    (* 3: STAR→DELTA transition — open star, close delta *)`,
      `    3:`,
      `      starContactorCmd := FALSE;`,
      `      (* Brief dead-time (handled by next scan) then close delta *)`,
      `      deltaContactorCmd := TRUE;`,
      `      contactorCheckTimer(IN := TRUE, PT := T#2s);`,
      `      IF contactorCheckTimer.Q THEN`,
      `        contactorCheckTimer(IN := FALSE);`,
      `        IF NOT motorContactor THEN`,
      `          faultCode := 3;`,
      `          state := 6;`,
      `        ELSE`,
      `          state := 4;  (* → RUNNING *)`,
      `        END_IF;`,
      `      END_IF;`,
      ``,
      `    (* 4: RUNNING — motor confirmed running, monitor continuously *)`,
      `    4:`,
      `      motorRunning := TRUE;`,
      ``,
      isVFD ? [
        `      (* VFD ramp-up to target speed *)`,
        `      IF rampValue < speedRef THEN`,
        `        rampValue := rampValue + rampIncrement;`,
        `        IF rampValue > speedRef THEN rampValue := speedRef; END_IF;`,
        `      ELSIF rampValue > speedRef THEN`,
        `        rampValue := rampValue - rampDecrement;`,
        `        IF rampValue < speedRef THEN rampValue := speedRef; END_IF;`,
        `      END_IF;`,
        `      vfdSpeedOut := rampValue;`,
      ].join("\n") : ``,
      ``,
      `      (* --- Overload detection --- *)`,
      `      overloadTimer(IN := currentFB > overloadLimit, PT := overloadDelay);`,
      `      IF overloadTimer.Q THEN`,
      `        faultCode := 1;`,
      `        state := 6;  (* → FAULT *)`,
      `      END_IF;`,
      ``,
      `      (* --- Thermal protection --- *)`,
      `      IF thermalInput > 150.0 THEN  (* 150°C = Class F limit *)`,
      `        faultCode := 2;`,
      `        state := 6;  (* → FAULT *)`,
      `      END_IF;`,
      ``,
      isVFD ? [
        `      (* --- VFD fault monitoring --- *)`,
        `      IF vfdFault THEN`,
        `        faultCode := 4;`,
        `        state := 6;  (* → FAULT *)`,
        `      END_IF;`,
      ].join("\n") : ``,
      ``,
      `      (* --- Stop command --- *)`,
      `      IF cmdStop OR NOT enableRun THEN`,
      `        state := 5;  (* → STOPPING *)`,
      `      END_IF;`,
      ``,
      `      (* --- Run hours accumulator --- *)`,
      `      runTimer(IN := TRUE, PT := T#1h);`,
      `      IF runTimer.Q THEN`,
      `        runHours := runHours + 1.0;`,
      `        runTimer(IN := FALSE);`,
      `      END_IF;`,
      ``,
      `    (* 5: STOPPING — controlled deceleration *)`,
      `    5:`,
      isVFD ? [
        `      (* VFD ramp-down *)`,
        `      rampValue := rampValue - rampDecrement;`,
        `      IF rampValue <= 0.0 THEN`,
        `        rampValue := 0.0;`,
        `        vfdSpeedOut := 0.0;`,
        `        vfdRunCmd := FALSE;`,
        `        contactorCmd := FALSE;`,
        `        deltaContactorCmd := FALSE;`,
        `        motorRunning := FALSE;`,
        `        restartAllowed := FALSE;`,
        `        state := 0;  (* → IDLE *)`,
        `      ELSE`,
        `        vfdSpeedOut := rampValue;`,
        `      END_IF;`,
      ].join("\n") : [
        `      (* DOL: immediate stop *)`,
        `      contactorCmd := FALSE;`,
        `      deltaContactorCmd := FALSE;`,
        `      starContactorCmd := FALSE;`,
        `      motorRunning := FALSE;`,
        `      restartAllowed := FALSE;`,
        `      state := 0;  (* → IDLE *)`,
      ].join("\n"),
      ``,
      `    (* 6: FAULT — all outputs off, wait for reset *)`,
      `    6:`,
      `      contactorCmd := FALSE;`,
      isVFD ? `      vfdRunCmd := FALSE;` : ``,
      isVFD ? `      vfdSpeedOut := 0.0;` : ``,
      isVFD ? `      rampValue := 0.0;` : ``,
      `      starContactorCmd := FALSE;`,
      `      deltaContactorCmd := FALSE;`,
      `      motorRunning := FALSE;`,
      `      motorFault := TRUE;`,
      ``,
      `      IF resetEdge.Q AND safetyOk AND currentFB < overloadLimit AND thermalInput < 130.0 THEN`,
      `        motorFault := FALSE;`,
      `        faultCode := 0;`,
      `        restartAllowed := FALSE;  (* Enforce lockout before next start *)`,
      `        state := 0;  (* → IDLE *)`,
      `      END_IF;`,
      ``,
      `  END_CASE;`,
      ``,
      `END_FUNCTION_BLOCK`,
    ].filter(line => line !== "").join("\n");
  },
  getValveControlTemplate(valve: ValveSpec): string {
    const isProportional = valve.type === "proportional";
    const hasFeedback = valve.feedbackType !== "none";
    return [
      `FUNCTION_BLOCK FB_Valve_${valve.name}`,
      `(* ============================================================`,
      `   Valve Control — Inovance AM600 / EtherCAT`,
      `   Valve: ${valve.name}, Type: ${valve.type}`,
      `   Feedback: ${valve.feedbackType}, Station: ${valve.stationCode}`,
      `   Features: Open/close with feedback verification, timeout`,
      `             detection, proportional output (0-100%),`,
      `             stuck-valve alarm, travel time monitoring`,
      `   ============================================================ *)`,
      ``,
      `  VAR_INPUT`,
      `    cmdOpen        : BOOL;   (* Open command *)`,
      `    cmdClose       : BOOL;   (* Close command *)`,
      `    safetyOk       : BOOL;   (* Safety chain status *)`,
      `    enableValve    : BOOL;   (* Permissive from mode manager *)`,
      isProportional ? `    positionCmd    : REAL := 0.0;  (* Proportional command 0..100% *)` : ``,
      hasFeedback ? `    fbOpen         AT %IX${70}.0 : BOOL;  (* Open limit switch / proximity *)` : ``,
      hasFeedback ? `    fbClosed       AT %IX${70}.1 : BOOL;  (* Closed limit switch / proximity *)` : ``,
      isProportional ? `    positionFB     AT %IW${72} : REAL;  (* Analog position feedback 0..100% *)` : ``,
      `    travelTimeout  : TIME := T#10s;  (* Max time to travel open↔closed *)`,
      `    stuckRetries   : INT := 3;       (* Retry attempts before stuck alarm *)`,
      isProportional ? `    posTolerance   : REAL := 2.0;  (* Position tolerance band [%] *)` : ``,
      `    cmdReset       : BOOL;   (* Fault reset *)`,
      `  END_VAR`,
      ``,
      `  VAR_OUTPUT`,
      `    valveOpen      : BOOL;   (* Valve confirmed open *)`,
      `    valveClosed    : BOOL;   (* Valve confirmed closed *)`,
      `    valveTransit   : BOOL;   (* Valve in motion *)`,
      `    valveFault     : BOOL;   (* Latched fault *)`,
      `    stuckAlarm     : BOOL;   (* Valve stuck — failed to reach position *)`,
      `    faultCode      : INT;    (* 0=OK, 1=OpenTimeout, 2=CloseTimeout, 3=Stuck, 4=FeedbackConflict, 5=Safety *)`,
      `    solenoidOpen   AT %QX${74}.0 : BOOL;  (* Solenoid output: open direction *)`,
      `    solenoidClose  AT %QX${74}.1 : BOOL;  (* Solenoid output: close direction *)`,
      isProportional ? `    analogOut      AT %QW${76} : REAL;  (* Proportional output 0..100% → 4-20mA *)` : ``,
      `    travelTimeMs   : DINT;   (* Last measured travel time [ms] *)`,
      `  END_VAR`,
      ``,
      `  VAR`,
      `    state          : INT := 0;  (* 0=IDLE_CLOSED, 1=OPENING, 2=OPEN, 3=CLOSING, 4=FAULT *)`,
      `    openTimer      : TON;       (* Timeout for open travel *)`,
      `    closeTimer     : TON;       (* Timeout for close travel *)`,
      `    retryCount     : INT := 0;`,
      `    resetEdge      : R_TRIG;`,
      `    openEdge       : R_TRIG;`,
      `    closeEdge      : R_TRIG;`,
      `    travelStartMs  : DINT := 0;`,
      `    sysTimeMs      : DINT;      (* System millisecond counter placeholder *)`,
      isProportional ? `    posError       : REAL;` : ``,
      isProportional ? `    posReached     : BOOL;` : ``,
      `  END_VAR`,
      ``,
      `  (* ---- Edge detection ---- *)`,
      `  openEdge(CLK := cmdOpen);`,
      `  closeEdge(CLK := cmdClose);`,
      `  resetEdge(CLK := cmdReset);`,
      ``,
      `  (* ---- Safety override ---- *)`,
      `  IF NOT safetyOk OR NOT enableValve THEN`,
      `    solenoidOpen := FALSE;`,
      `    solenoidClose := FALSE;`,
      isProportional ? `    analogOut := 0.0;` : ``,
      `    IF state <> 4 AND NOT safetyOk THEN`,
      `      faultCode := 5;`,
      `      state := 4;  (* → FAULT *)`,
      `    END_IF;`,
      `  END_IF;`,
      ``,
      hasFeedback ? [
        `  (* ---- Feedback conflict detection ---- *)`,
        `  (* Both open AND closed at same time = wiring fault *)`,
        `  IF fbOpen AND fbClosed THEN`,
        `    faultCode := 4;`,
        `    solenoidOpen := FALSE;`,
        `    solenoidClose := FALSE;`,
        `    state := 4;  (* → FAULT *)`,
        `  END_IF;`,
      ].join("\n") : ``,
      ``,
      `  (* ---- Main state machine ---- *)`,
      `  CASE state OF`,
      ``,
      `    (* 0: IDLE / CLOSED — default safe state *)`,
      `    0:`,
      `      solenoidOpen := FALSE;`,
      `      solenoidClose := FALSE;`,
      isProportional ? `      analogOut := 0.0;` : ``,
      `      valveOpen := FALSE;`,
      hasFeedback ? `      valveClosed := fbClosed;` : `      valveClosed := TRUE;`,
      `      valveTransit := FALSE;`,
      ``,
      `      IF (openEdge.Q OR cmdOpen) AND safetyOk AND enableValve AND NOT valveFault THEN`,
      `        state := 1;  (* → OPENING *)`,
      `        openTimer(IN := FALSE);  (* Reset *)`,
      `        travelStartMs := sysTimeMs;`,
      `      END_IF;`,
      ``,
      `    (* 1: OPENING — solenoid energized open, waiting for feedback *)`,
      `    1:`,
      `      solenoidOpen := TRUE;`,
      `      solenoidClose := FALSE;`,
      isProportional ? [
        `      (* Proportional: ramp to commanded position *)`,
        `      IF analogOut < positionCmd THEN`,
        `        analogOut := analogOut + 1.0;  (* ~1%/scan ramp *)`,
        `        IF analogOut > positionCmd THEN analogOut := positionCmd; END_IF;`,
        `      ELSE`,
        `        analogOut := positionCmd;`,
        `      END_IF;`,
      ].join("\n") : ``,
      `      valveTransit := TRUE;`,
      `      valveClosed := FALSE;`,
      ``,
      hasFeedback ? [
        `      (* Check if open position reached *)`,
        isProportional ? [
          `      posError := ABS(positionFB - positionCmd);`,
          `      posReached := posError <= posTolerance;`,
          `      IF posReached THEN`,
        ].join("\n") : `      IF fbOpen THEN`,
        `        travelTimeMs := sysTimeMs - travelStartMs;`,
        `        valveOpen := TRUE;`,
        `        valveTransit := FALSE;`,
        `        retryCount := 0;`,
        `        state := 2;  (* → OPEN *)`,
        `      END_IF;`,
      ].join("\n") : [
        `      (* No feedback: assume open after half travel timeout *)`,
        `      openTimer(IN := TRUE, PT := T#5s);`,
        `      IF openTimer.Q THEN`,
        `        valveOpen := TRUE;`,
        `        valveTransit := FALSE;`,
        `        state := 2;  (* → OPEN *)`,
        `      END_IF;`,
      ].join("\n"),
      ``,
      `      (* Timeout detection *)`,
      `      openTimer(IN := TRUE, PT := travelTimeout);`,
      `      IF openTimer.Q${hasFeedback ? " AND NOT " + (isProportional ? "posReached" : "fbOpen") : ""} THEN`,
      `        retryCount := retryCount + 1;`,
      `        IF retryCount >= stuckRetries THEN`,
      `          stuckAlarm := TRUE;`,
      `          faultCode := 3;  (* Stuck *)`,
      `          state := 4;  (* → FAULT *)`,
      `        ELSE`,
      `          (* Retry: toggle solenoid off then on *)`,
      `          solenoidOpen := FALSE;`,
      `          faultCode := 1;  (* Open timeout — retrying *)`,
      `          openTimer(IN := FALSE);`,
      `          (* Will re-enter OPENING on next scan since cmdOpen still true *)`,
      `        END_IF;`,
      `      END_IF;`,
      ``,
      `    (* 2: OPEN — valve in open position *)`,
      `    2:`,
      `      solenoidOpen := TRUE;  (* Hold open *)`,
      `      solenoidClose := FALSE;`,
      isProportional ? `      analogOut := positionCmd;  (* Hold proportional position *)` : ``,
      `      valveOpen := TRUE;`,
      `      valveClosed := FALSE;`,
      `      valveTransit := FALSE;`,
      ``,
      isProportional ? [
        `      (* Continuous position tracking for proportional valves *)`,
        `      posError := ABS(positionFB - positionCmd);`,
        `      IF posError > posTolerance * 3.0 THEN`,
        `        (* Position drifted too far — re-enter transit *)`,
        `        state := 1;`,
        `      END_IF;`,
      ].join("\n") : ``,
      ``,
      `      IF (closeEdge.Q OR cmdClose) AND safetyOk THEN`,
      `        state := 3;  (* → CLOSING *)`,
      `        closeTimer(IN := FALSE);`,
      `        travelStartMs := sysTimeMs;`,
      `      END_IF;`,
      ``,
      `    (* 3: CLOSING — solenoid de-energized / close energized *)`,
      `    3:`,
      `      solenoidOpen := FALSE;`,
      `      solenoidClose := TRUE;`,
      isProportional ? [
        `      (* Ramp down proportional output *)`,
        `      IF analogOut > 0.0 THEN`,
        `        analogOut := analogOut - 1.0;`,
        `        IF analogOut < 0.0 THEN analogOut := 0.0; END_IF;`,
        `      END_IF;`,
      ].join("\n") : ``,
      `      valveTransit := TRUE;`,
      `      valveOpen := FALSE;`,
      ``,
      hasFeedback ? [
        isProportional ? [
          `      IF positionFB <= posTolerance THEN`,
        ].join("\n") : `      IF fbClosed THEN`,
        `        travelTimeMs := sysTimeMs - travelStartMs;`,
        `        valveClosed := TRUE;`,
        `        valveTransit := FALSE;`,
        `        retryCount := 0;`,
        `        state := 0;  (* → IDLE_CLOSED *)`,
        `      END_IF;`,
      ].join("\n") : [
        `      closeTimer(IN := TRUE, PT := T#5s);`,
        `      IF closeTimer.Q THEN`,
        `        valveClosed := TRUE;`,
        `        valveTransit := FALSE;`,
        `        state := 0;`,
        `      END_IF;`,
      ].join("\n"),
      ``,
      `      (* Close timeout *)`,
      `      closeTimer(IN := TRUE, PT := travelTimeout);`,
      `      IF closeTimer.Q${hasFeedback ? " AND NOT " + (isProportional ? "(positionFB <= posTolerance)" : "fbClosed") : ""} THEN`,
      `        retryCount := retryCount + 1;`,
      `        IF retryCount >= stuckRetries THEN`,
      `          stuckAlarm := TRUE;`,
      `          faultCode := 3;`,
      `          state := 4;  (* → FAULT *)`,
      `        ELSE`,
      `          faultCode := 2;  (* Close timeout — retrying *)`,
      `          closeTimer(IN := FALSE);`,
      `        END_IF;`,
      `      END_IF;`,
      ``,
      `    (* 4: FAULT — outputs safe, wait for reset *)`,
      `    4:`,
      `      solenoidOpen := FALSE;`,
      `      solenoidClose := FALSE;`,
      isProportional ? `      analogOut := 0.0;` : ``,
      `      valveOpen := FALSE;`,
      `      valveClosed := FALSE;`,
      `      valveTransit := FALSE;`,
      `      valveFault := TRUE;`,
      ``,
      `      IF resetEdge.Q AND safetyOk THEN`,
      `        valveFault := FALSE;`,
      `        stuckAlarm := FALSE;`,
      `        faultCode := 0;`,
      `        retryCount := 0;`,
      `        state := 0;  (* → IDLE_CLOSED *)`,
      `      END_IF;`,
      ``,
      `  END_CASE;`,
      ``,
      `END_FUNCTION_BLOCK`,
    ].filter(line => line !== "").join("\n");
  },
  getPidTemplate(pid: PidSpec): string {
    return [
      `FUNCTION_BLOCK FB_PID_${pid.name}`,
      `(* ============================================================`,
      `   PID Controller with Anti-Windup — Inovance AM600`,
      `   Process: ${pid.processVariable}, Setpoint: ${pid.setpoint}`,
      `   Output type: ${pid.outputType}, Station: ${pid.stationCode}`,
      `   Features: Kp/Ki/Kd tuning, integral anti-windup (clamping),`,
      `             derivative filter, auto/manual bumpless transfer,`,
      `             output limiting, deviation alarm`,
      `   ============================================================ *)`,
      ``,
      `  VAR_INPUT`,
      `    enable        : BOOL;   (* Enable PID calculation *)`,
      `    autoMode      : BOOL;   (* TRUE=Auto PID, FALSE=Manual output *)`,
      `    setpoint      : REAL := ${pid.setpoint.toFixed(1)};  (* SP — desired value *)`,
      `    processValue  AT %IW${100} : REAL;  (* PV — measured value from sensor *)`,
      `    manualOutput  : REAL := 0.0;  (* Manual output when autoMode=FALSE *)`,
      `    Kp            : REAL := 1.0;  (* Proportional gain *)`,
      `    Ki            : REAL := 0.1;  (* Integral gain [1/s] *)`,
      `    Kd            : REAL := 0.05; (* Derivative gain [s] *)`,
      `    cycleTime     : REAL := 0.01; (* Scan cycle time [s] — default 10ms *)`,
      `    outputMin     : REAL := 0.0;  (* Output lower limit *)`,
      `    outputMax     : REAL := 100.0; (* Output upper limit *)`,
      `    deadband      : REAL := 0.5;  (* Error deadband — no action if |error| < deadband *)`,
      `    derivFilter   : REAL := 0.1;  (* Derivative filter coeff 0..1, higher = more filter *)`,
      `    deviationHigh : REAL := 20.0; (* High deviation alarm threshold *)`,
      `    resetIntegral : BOOL;  (* Manual reset of integral term *)`,
      `  END_VAR`,
      ``,
      `  VAR_OUTPUT`,
      `    output        AT %QW${200} : REAL;  (* Control output 0..100% *)`,
      `    error         : REAL;   (* Current error = SP - PV *)`,
      `    pTerm         : REAL;   (* Proportional contribution *)`,
      `    iTerm         : REAL;   (* Integral contribution *)`,
      `    dTerm         : REAL;   (* Derivative contribution *)`,
      `    outputLimited : BOOL;   (* TRUE when output is clamped *)`,
      `    deviationAlarm: BOOL;   (* TRUE when |error| > deviationHigh *)`,
      `    atSetpoint    : BOOL;   (* TRUE when |error| <= deadband *)`,
      `  END_VAR`,
      ``,
      `  VAR`,
      `    integralSum   : REAL := 0.0;  (* Accumulated integral *)`,
      `    prevError     : REAL := 0.0;  (* Previous error for derivative *)`,
      `    prevPV        : REAL := 0.0;  (* Previous PV for derivative-on-PV *)`,
      `    prevDerivRaw  : REAL := 0.0;  (* Previous raw derivative for filter *)`,
      `    rawOutput     : REAL := 0.0;  (* Pre-clamping output *)`,
      `    derivRaw      : REAL := 0.0;  (* Unfiltered derivative *)`,
      `    prevAutoMode  : BOOL := FALSE; (* For bumpless transfer detection *)`,
      `    windupActive  : BOOL := FALSE; (* Anti-windup flag *)`,
      `  END_VAR`,
      ``,
      `  (* ============================================================`,
      `     STEP 0: Disabled state — zero output`,
      `     ============================================================ *)`,
      `  IF NOT enable THEN`,
      `    output := 0.0;`,
      `    integralSum := 0.0;`,
      `    prevError := 0.0;`,
      `    prevPV := processValue;`,
      `    prevDerivRaw := 0.0;`,
      `    pTerm := 0.0;`,
      `    iTerm := 0.0;`,
      `    dTerm := 0.0;`,
      `    outputLimited := FALSE;`,
      `    atSetpoint := FALSE;`,
      `    deviationAlarm := FALSE;`,
      `    RETURN;`,
      `  END_IF;`,
      ``,
      `  (* ============================================================`,
      `     STEP 1: Error calculation`,
      `     ============================================================ *)`,
      `  error := setpoint - processValue;`,
      ``,
      `  (* Deviation alarm *)`,
      `  deviationAlarm := ABS(error) > deviationHigh;`,
      ``,
      `  (* At-setpoint flag (within deadband) *)`,
      `  atSetpoint := ABS(error) <= deadband;`,
      ``,
      `  (* ============================================================`,
      `     STEP 2: Manual mode — direct output, track integral`,
      `     ============================================================ *)`,
      `  IF NOT autoMode THEN`,
      `    output := manualOutput;`,
      `    (* Clamp manual output *)`,
      `    IF output > outputMax THEN output := outputMax; END_IF;`,
      `    IF output < outputMin THEN output := outputMin; END_IF;`,
      `    (* Track integral to current output for bumpless transfer *)`,
      `    IF ABS(Kp) > 1.0E-6 THEN`,
      `      integralSum := output - (Kp * error);  (* Back-calculate I term *)`,
      `    ELSE`,
      `      integralSum := output;`,
      `    END_IF;`,
      `    prevError := error;`,
      `    prevPV := processValue;`,
      `    prevAutoMode := FALSE;`,
      `    pTerm := 0.0;`,
      `    iTerm := integralSum;`,
      `    dTerm := 0.0;`,
      `    outputLimited := (manualOutput > outputMax) OR (manualOutput < outputMin);`,
      `    RETURN;`,
      `  END_IF;`,
      ``,
      `  (* ============================================================`,
      `     STEP 2B: Bumpless transfer — manual → auto`,
      `     On first scan in auto, re-initialize integral to match`,
      `     current output so there is no output jump.`,
      `     ============================================================ *)`,
      `  IF autoMode AND NOT prevAutoMode THEN`,
      `    (* integralSum already tracked in manual mode — no action needed *)`,
      `    prevError := error;`,
      `    prevPV := processValue;`,
      `  END_IF;`,
      `  prevAutoMode := autoMode;`,
      ``,
      `  (* ============================================================`,
      `     STEP 3: Proportional term`,
      `     ============================================================ *)`,
      `  IF ABS(error) > deadband THEN`,
      `    pTerm := Kp * error;`,
      `  ELSE`,
      `    pTerm := 0.0;  (* Inside deadband — no proportional action *)`,
      `  END_IF;`,
      ``,
      `  (* ============================================================`,
      `     STEP 4: Integral term with anti-windup (clamping)`,
      `     Only integrate when output is not saturated, OR when the`,
      `     integration would move output away from the limit.`,
      `     ============================================================ *)`,
      `  IF resetIntegral THEN`,
      `    integralSum := 0.0;`,
      `  ELSIF NOT windupActive OR (error * integralSum < 0.0) THEN`,
      `    (* Integrate only if: not in windup, OR error sign opposes integral *)`,
      `    integralSum := integralSum + (Ki * error * cycleTime);`,
      `  END_IF;`,
      `  iTerm := integralSum;`,
      ``,
      `  (* ============================================================`,
      `     STEP 5: Derivative term (derivative-on-PV to avoid SP kick)`,
      `     with first-order low-pass filter`,
      `     ============================================================ *)`,
      `  IF cycleTime > 1.0E-6 THEN`,
      `    derivRaw := -Kd * (processValue - prevPV) / cycleTime;`,
      `  ELSE`,
      `    derivRaw := 0.0;`,
      `  END_IF;`,
      `  (* Low-pass filter: dTerm = alpha * raw + (1-alpha) * prev *)`,
      `  dTerm := derivFilter * prevDerivRaw + (1.0 - derivFilter) * derivRaw;`,
      `  prevDerivRaw := dTerm;`,
      `  prevError := error;`,
      `  prevPV := processValue;`,
      ``,
      `  (* ============================================================`,
      `     STEP 6: Sum and clamp output`,
      `     ============================================================ *)`,
      `  rawOutput := pTerm + iTerm + dTerm;`,
      ``,
      `  (* Output clamping *)`,
      `  IF rawOutput > outputMax THEN`,
      `    output := outputMax;`,
      `    outputLimited := TRUE;`,
      `    windupActive := TRUE;`,
      `  ELSIF rawOutput < outputMin THEN`,
      `    output := outputMin;`,
      `    outputLimited := TRUE;`,
      `    windupActive := TRUE;`,
      `  ELSE`,
      `    output := rawOutput;`,
      `    outputLimited := FALSE;`,
      `    windupActive := FALSE;`,
      `  END_IF;`,
      ``,
      `END_FUNCTION_BLOCK`,
    ].join("\n");
  },
  getAlarmBlockTemplate(alarms: AlarmDef[]): string {
    const maxIdx = Math.max(alarms.length - 1, 0);
    const bufferSize = 64; // Circular alarm history buffer
    // Generate alarm constant declarations from AlarmDef array
    const alarmConstants = alarms.map((a, i) => [
      `    (* Alarm ${i}: ${a.code} — ${a.message} / ${a.messageEn} *)`,
      `    (* Severity: ${a.severity}, Reset: ${a.resetType}, Interlock: ${a.interlockAction} *)`,
    ].join("\n")).join("\n");
    // Generate severity array initializer
    const severityMap: Record<string, number> = { critical: 1, high: 2, medium: 3, low: 4 };
    const severityInit = alarms.map((a) => `${severityMap[a.severity] ?? 4}`).join(", ");
    // Generate reset-type flags
    const autoResetFlags = alarms.map((a) => a.resetType === "auto" ? "TRUE" : "FALSE").join(", ");

    return [
      `FUNCTION_BLOCK FB_AlarmManager`,
      `(* ============================================================`,
      `   Alarm Manager — Inovance AM600 / EtherCAT`,
      `   Alarm count: ${alarms.length}, Buffer: ${bufferSize} entries`,
      `   Features: 5 priority levels, circular alarm buffer/queue,`,
      `             individual acknowledge, auto-reset for transient`,
      `             alarms, alarm history with timestamps, interlock`,
      `             action output, highest-priority tracking`,
      `   ============================================================ *)`,
      ``,
      alarmConstants,
      ``,
      `  VAR_INPUT`,
      `    triggers       : ARRAY[0..${maxIdx}] OF BOOL;  (* Raw alarm trigger inputs *)`,
      `    ackSingle      : INT := -1;   (* Acknowledge single alarm by index, -1=none *)`,
      `    ackAll         : BOOL;        (* Acknowledge all alarms *)`,
      `    resetAll       : BOOL;        (* Reset all acknowledged alarms *)`,
      `    systemTimeMs   : DINT;        (* System millisecond timestamp for history *)`,
      `    enableHistory  : BOOL := TRUE; (* Enable alarm history recording *)`,
      `  END_VAR`,
      ``,
      `  VAR_OUTPUT`,
      `    active         : ARRAY[0..${maxIdx}] OF BOOL;  (* Currently active alarms *)`,
      `    acknowledged   : ARRAY[0..${maxIdx}] OF BOOL;  (* Acknowledged but not cleared *)`,
      `    activeCount    : INT;     (* Number of currently active alarms *)`,
      `    unackedCount   : INT;     (* Active but not yet acknowledged *)`,
      `    highestPriority: INT;     (* Highest (lowest number) active alarm priority, 0=none *)`,
      `    highestAlarmIdx: INT;     (* Index of highest priority active alarm *)`,
      `    interlockStop  : BOOL;    (* TRUE if any critical alarm requires machine stop *)`,
      `    interlockWarn  : BOOL;    (* TRUE if any high alarm requires speed reduction *)`,
      `    hornOutput     AT %QX${80}.0 : BOOL;  (* Audible alarm horn *)`,
      `    beaconRed      AT %QX${80}.1 : BOOL;  (* Red stack light *)`,
      `    beaconYellow   AT %QX${80}.2 : BOOL;  (* Yellow stack light *)`,
      `    historyPtr     : INT;     (* Current position in history buffer *)`,
      `    historyFull    : BOOL;    (* History buffer has wrapped *)`,
      `  END_VAR`,
      ``,
      `  VAR`,
      `    severity       : ARRAY[0..${maxIdx}] OF INT := [${severityInit}];  (* 1=Critical..5=Low *)`,
      `    autoReset      : ARRAY[0..${maxIdx}] OF BOOL := [${autoResetFlags}];  (* Auto-reset capable *)`,
      `    prevTriggers   : ARRAY[0..${maxIdx}] OF BOOL;   (* Previous scan triggers for edge detect *)`,
      `    activateTime   : ARRAY[0..${maxIdx}] OF DINT;   (* Timestamp when alarm activated *)`,
      `    historyCode    : ARRAY[0..${bufferSize - 1}] OF INT;    (* Alarm index in history *)`,
      `    historyTime    : ARRAY[0..${bufferSize - 1}] OF DINT;   (* Activation timestamp *)`,
      `    historyEvent   : ARRAY[0..${bufferSize - 1}] OF INT;    (* 1=Activated, 2=Acked, 3=Cleared *)`,
      `    i              : INT;`,
      `    ackEdge        : R_TRIG;`,
      `    resetEdge      : R_TRIG;`,
      `    flashTimer     : TON;`,
      `    flashState     : BOOL;    (* 1Hz flash for unacknowledged *)`,
      `    autoResetDelay : ARRAY[0..${maxIdx}] OF TON;  (* Delay before auto-reset *)`,
      `  END_VAR`,
      ``,
      `  (* ---- Edge detection ---- *)`,
      `  ackEdge(CLK := ackAll);`,
      `  resetEdge(CLK := resetAll);`,
      ``,
      `  (* ---- Flash generator (1Hz) for unacknowledged alarms ---- *)`,
      `  flashTimer(IN := NOT flashState, PT := T#500ms);`,
      `  IF flashTimer.Q THEN`,
      `    flashState := NOT flashState;`,
      `    flashTimer(IN := FALSE);`,
      `  END_IF;`,
      ``,
      `  (* ============================================================`,
      `     STEP 1: Process each alarm trigger`,
      `     ============================================================ *)`,
      `  activeCount := 0;`,
      `  unackedCount := 0;`,
      `  highestPriority := 0;`,
      `  highestAlarmIdx := -1;`,
      `  interlockStop := FALSE;`,
      `  interlockWarn := FALSE;`,
      ``,
      `  FOR i := 0 TO ${maxIdx} DO`,
      ``,
      `    (* --- Alarm activation on rising edge --- *)`,
      `    IF triggers[i] AND NOT prevTriggers[i] THEN`,
      `      IF NOT active[i] THEN`,
      `        active[i] := TRUE;`,
      `        acknowledged[i] := FALSE;`,
      `        activateTime[i] := systemTimeMs;`,
      `        (* Record in history buffer *)`,
      `        IF enableHistory THEN`,
      `          historyCode[historyPtr] := i;`,
      `          historyTime[historyPtr] := systemTimeMs;`,
      `          historyEvent[historyPtr] := 1;  (* Activated *)`,
      `          historyPtr := (historyPtr + 1) MOD ${bufferSize};`,
      `          IF historyPtr = 0 THEN historyFull := TRUE; END_IF;`,
      `        END_IF;`,
      `      END_IF;`,
      `    END_IF;`,
      `    prevTriggers[i] := triggers[i];`,
      ``,
      `    (* --- Auto-reset for transient alarms --- *)`,
      `    (* If trigger clears and alarm is auto-reset type, clear after 2s *)`,
      `    IF active[i] AND autoReset[i] AND NOT triggers[i] THEN`,
      `      autoResetDelay[i](IN := TRUE, PT := T#2s);`,
      `      IF autoResetDelay[i].Q THEN`,
      `        active[i] := FALSE;`,
      `        acknowledged[i] := FALSE;`,
      `        autoResetDelay[i](IN := FALSE);`,
      `        (* Record clear in history *)`,
      `        IF enableHistory THEN`,
      `          historyCode[historyPtr] := i;`,
      `          historyTime[historyPtr] := systemTimeMs;`,
      `          historyEvent[historyPtr] := 3;  (* Auto-cleared *)`,
      `          historyPtr := (historyPtr + 1) MOD ${bufferSize};`,
      `          IF historyPtr = 0 THEN historyFull := TRUE; END_IF;`,
      `        END_IF;`,
      `      END_IF;`,
      `    ELSE`,
      `      autoResetDelay[i](IN := FALSE);`,
      `    END_IF;`,
      ``,
      `    (* --- Single alarm acknowledge --- *)`,
      `    IF ackSingle = i AND active[i] AND NOT acknowledged[i] THEN`,
      `      acknowledged[i] := TRUE;`,
      `      IF enableHistory THEN`,
      `        historyCode[historyPtr] := i;`,
      `        historyTime[historyPtr] := systemTimeMs;`,
      `        historyEvent[historyPtr] := 2;  (* Acknowledged *)`,
      `        historyPtr := (historyPtr + 1) MOD ${bufferSize};`,
      `        IF historyPtr = 0 THEN historyFull := TRUE; END_IF;`,
      `      END_IF;`,
      `    END_IF;`,
      ``,
      `    (* --- Global acknowledge --- *)`,
      `    IF ackEdge.Q AND active[i] AND NOT acknowledged[i] THEN`,
      `      acknowledged[i] := TRUE;`,
      `    END_IF;`,
      ``,
      `    (* --- Global reset (only acknowledged alarms with trigger cleared) --- *)`,
      `    IF resetEdge.Q AND active[i] AND acknowledged[i] AND NOT triggers[i] THEN`,
      `      active[i] := FALSE;`,
      `      acknowledged[i] := FALSE;`,
      `      IF enableHistory THEN`,
      `        historyCode[historyPtr] := i;`,
      `        historyTime[historyPtr] := systemTimeMs;`,
      `        historyEvent[historyPtr] := 3;  (* Cleared *)`,
      `        historyPtr := (historyPtr + 1) MOD ${bufferSize};`,
      `        IF historyPtr = 0 THEN historyFull := TRUE; END_IF;`,
      `      END_IF;`,
      `    END_IF;`,
      ``,
      `    (* --- Counters and priority tracking --- *)`,
      `    IF active[i] THEN`,
      `      activeCount := activeCount + 1;`,
      `      IF NOT acknowledged[i] THEN`,
      `        unackedCount := unackedCount + 1;`,
      `      END_IF;`,
      `      (* Track highest priority (lowest number = highest priority) *)`,
      `      IF highestPriority = 0 OR severity[i] < highestPriority THEN`,
      `        highestPriority := severity[i];`,
      `        highestAlarmIdx := i;`,
      `      END_IF;`,
      `      (* Interlock actions based on severity *)`,
      `      IF severity[i] = 1 THEN`,
      `        interlockStop := TRUE;   (* Critical → immediate stop *)`,
      `      END_IF;`,
      `      IF severity[i] <= 2 THEN`,
      `        interlockWarn := TRUE;   (* High or Critical → warning *)`,
      `      END_IF;`,
      `    END_IF;`,
      ``,
      `  END_FOR;`,
      ``,
      `  (* ============================================================`,
      `     STEP 2: Output signaling`,
      `     ============================================================ *)`,
      `  (* Horn: sounds for unacknowledged alarms *)`,
      `  hornOutput := unackedCount > 0;`,
      ``,
      `  (* Red beacon: critical or high alarm active *)`,
      `  IF highestPriority >= 1 AND highestPriority <= 2 AND activeCount > 0 THEN`,
      `    IF unackedCount > 0 THEN`,
      `      beaconRed := flashState;  (* Flash if unacknowledged *)`,
      `    ELSE`,
      `      beaconRed := TRUE;        (* Steady if acknowledged *)`,
      `    END_IF;`,
      `  ELSE`,
      `    beaconRed := FALSE;`,
      `  END_IF;`,
      ``,
      `  (* Yellow beacon: medium or low alarm active *)`,
      `  IF highestPriority >= 3 AND activeCount > 0 THEN`,
      `    IF unackedCount > 0 THEN`,
      `      beaconYellow := flashState;`,
      `    ELSE`,
      `      beaconYellow := TRUE;`,
      `    END_IF;`,
      `  ELSE`,
      `    beaconYellow := FALSE;`,
      `  END_IF;`,
      ``,
      `END_FUNCTION_BLOCK`,
    ].join("\n");
  },
  getRecipeManagerTemplate(sc: number): string { return `FUNCTION_BLOCK FB_RecipeManager\n  VAR_INPUT load:BOOL; num:INT; END_VAR\n  VAR_OUTPUT loaded:BOOL; END_VAR\n  IF load AND num>=1 THEN loaded:=TRUE; END_IF;\nEND_FUNCTION_BLOCK`; },
  getDiagnosticTemplate(): string { return `FUNCTION_BLOCK FB_DiagnosticLog\n  VAR_INPUT logEntry:BOOL; code:INT; severity:INT; END_VAR\n  VAR_OUTPUT total,errors:INT; END_VAR\n  VAR ptr:INT:=0; prev:BOOL; END_VAR\n  IF logEntry AND NOT prev THEN ptr:=(ptr+1) MOD 200; total:=total+1; END_IF;\n  IF severity>=2 THEN errors:=errors+1; END_IF;\n  prev:=logEntry;\nEND_FUNCTION_BLOCK`; },
  getCommunicationTemplate(s: number): string { return `FUNCTION_BLOCK FB_Communication\n  VAR_INPUT hmiOk:BOOL; END_VAR\n  VAR_OUTPUT heartbeat,timeout:BOOL; END_VAR\n  VAR hb:TON; ct:TON; st:BOOL; END_VAR\n  hb(IN:=NOT st,PT:=T#500ms); IF hb.Q THEN st:=NOT st; hb(IN:=FALSE); END_IF;\n  heartbeat:=st; ct(IN:=NOT hmiOk,PT:=T#10s); timeout:=ct.Q;\nEND_FUNCTION_BLOCK`; },

  getFileExtension(): string { return ".st"; },
  getProjectStructureInfo(): string { return "InoProShop项目结构\n├── POU/\n├── 全局变量/\n├── I/O配置 (EtherCAT)/\n└── 库管理/"; },
};

registerAdapter(inovanceAdapter);
registerAdapter({ ...inovanceAdapter, brandKey: "INOVANCE_H5U", brandName: "Inovance H5U", brandNameZh: "汇川 H5U",
  models: [
    { model: "H5U-1614MT", description: "经济型, 16DI/14DO", maxIO: 512 },
    { model: "H5U-3224MT", description: "标准型, 32DI/24DO", maxIO: 1024 },
  ],
});

export { inovanceAdapter };
